SELECT '1月' AS month FROM DUAL 
UNION ALL
SELECT '2月' AS month FROM DUAL
UNION ALL
SELECT '3月' AS month FROM DUAL
UNION ALL
SELECT '4月' AS month FROM DUAL
UNION ALL
SELECT '5月' AS month FROM DUAL
UNION ALL
SELECT '6月' AS month FROM DUAL
UNION ALL
SELECT '6月' AS month FROM DUAL
UNION ALL
SELECT '7月' AS month FROM DUAL
UNION ALL
SELECT '8月' AS month FROM DUAL
UNION ALL
SELECT '9月' AS month FROM DUAL
UNION ALL
SELECT '10月' AS month FROM DUAL
UNION ALL
SELECT '11月' AS month FROM DUAL
UNION ALL
SELECT '12月' AS month FROM DUAL

SELECT  
LARGE_CATE AS 大品类,
BUYER AS 经理,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
 AS 年月,
SUM(QTY) AS 数量,
SUM(AMOUNT) AS 销售额,
(SUM(AMOUNT) - SUM(COST)) AS 毛利额
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}
${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4)

GROUP BY 
LARGE_CATE ,
BUYER ,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
ORDER BY 
LARGE_CATE ,
BUYER 


SELECT DISTINCT 
AREA_CODE,
AREA_NAME 
FROM 
DIM_REGION

SELECT  DISTINCT  
SUBSTR(DATE1,1,4)||'年' AS 年份
FROM 
DM_GATHER_CUS_GOODS
ORDER BY 
SUBSTR(DATE1,1,4)||'年'

SELECT  
DISTINCT 
ATTRIBUTE
FROM  
DM_GATHER_CUS_GOODS
where attribute!='关联交易'

SELECT  
DISTINCT
LARGE_CATE ,
BUYER 
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}

${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4) 
${if(len(LARGE_CATE)=0,""," and LARGE_CATE in ('"+LARGE_CATE+"')")}
${if(len(BUYER)=0,""," and BUYER in ('"+BUYER+"')")}
ORDER BY 
LARGE_CATE,
BUYER

SELECT  
LARGE_CATE AS 大品类,
BUYER AS 经理,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
 AS 年月,
SUM(QTY) AS 数量,
SUM(AMOUNT) AS 销售额,
(SUM(AMOUNT) - SUM(COST)) AS 毛利额
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}

${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4) -1
GROUP BY 
LARGE_CATE ,
BUYER ,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
ORDER BY 
LARGE_CATE ,
BUYER 

SELECT  
DISTINCT
LARGE_CATE
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}

${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4) 

ORDER BY 
length(LARGE_CATE) asc 

SELECT  
DISTINCT
BUYER
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}

${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4) 



SELECT  
LARGE_CATE AS 大品类,
BUYER AS 经理,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
 AS 年月,
SUM(QTY) AS 数量,
SUM(AMOUNT) AS 销售额,
(SUM(AMOUNT) - SUM(COST)) AS 毛利额
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}
${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4)
and ATTRIBUTE!='关联交易'
GROUP BY 
LARGE_CATE ,
BUYER ,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
ORDER BY 
LARGE_CATE ,
BUYER 


SELECT  
LARGE_CATE AS 大品类,
BUYER AS 经理,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
 AS 年月,
SUM(QTY) AS 数量,
SUM(AMOUNT) AS 销售额,
(SUM(AMOUNT) - SUM(COST)) AS 毛利额
FROM  
DM_GATHER_CUS_GOODS
WHERE 
1=1 
${if(len(CUS)=0,""," and ATTRIBUTE in ('"+CUS+"')")}
and ATTRIBUTE!='关联交易'
${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
AND 
SUBSTR(DATE1,1,4) = SUBSTR('${YEAR}',1,4) -1
GROUP BY 
LARGE_CATE ,
BUYER ,
CASE WHEN 
SUBSTR(DATE1,6,7) >= '10' 
THEN 
SUBSTR(DATE1,6,7)||'月'
ELSE 
SUBSTR(DATE1,7,7)||'月'
END
ORDER BY 
LARGE_CATE ,
BUYER 

