SELECT DISTINCT CUS_CODE,CUS_NAME
FROM  DM_DELIVERY_SALE_STOCK
WHERE 
AREA_CODE = '${AREA_CODE}'
--1=1
--${if(len(AREA_CODE)=0,"", "and AREA_CODE in ('"+AREA_CODE+"')")} 

SELECT DISTINCT
DDATE AS 日期, 
WEEK_ID AS 第几周,
MONTH_ID||WEEK_ID as NEW_ID,
WEEK_DESC AS 星期几,
YEAR_ID AS 年份,
MONTH_ID AS 月份,
TO_CHAR(DDATE,'MM-dd') AS 日月日期
FROM DIM_DAY 
WHERE 
YEAR_ID = TO_CHAR(DATE'${DATE1}','YYYY')
AND 
DDATE <= 
(
select max(DDATE) 
from DIM_DAY 
where  
YEAR_ID = TO_CHAR(DATE'${DATE1}','YYYY') 
and 
WEEK_ID=
(select WEEK_ID from DIM_DAY 
where DDATE=to_date('${DATE1}','YYYY-MM-DD'))
)
ORDER BY DDATE





SELECT DISTINCT
DDATE AS 日期, 
WEEK_ID AS 第几周,
WEEK_DESC AS 星期几,
YEAR_ID AS 年份,
MONTH_ID AS 月份,
TO_CHAR(DDATE,'MM-dd') AS 日月日期
FROM DIM_DAY 
WHERE 
YEAR_ID = TO_CHAR(ADD_MONTHS(DATE'${DATE1}',-12),'YYYY')
--AND 
--DDATE <= ADD_MONTHS(DATE'${DATE1}',-12)
ORDER BY DDATE


SELECT 
SALE_DATE AS 日期,
ROUND(SUM(NO_TAX_AMOUNT),2) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本,
SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST) AS 无税毛利额,
SUM(SALE_QTY) AS 销售数量
FROM 
DM_SALE_TMP a,DIM_DAY b
WHERE 
AREA_CODE = '${AREA_CODE}'
AND
--TO_CHAR(CUS_CODE) = '${CUS}'
CUS_CODE = '${CUS}'

--1=1
--${if(len(CUS)=0,"", "and CUS_CODE in ('"+CUS+"')")} 
--${if(len(AREA_CODE)=0,"", "and AREA_CODE in ('"+AREA_CODE+"')")}
and a.SALE_DATE=b.DDATE
AND 
b.YEAR_ID= SUBSTR('${DATE1}',1,4)

GROUP BY SALE_DATE

SELECT 
--A.CUS_CODE,
SALE_DATE,
SUM(A.TRAN_NUM) AS 交易笔次
FROM 
DIM_DAY ss,DM_TRANSACTION A
LEFT JOIN 
DIM_CUS B
ON 
A.AREA_CODE = B.AREA_CODE 
AND 
TO_CHAR(A.CUS_CODE) = b.CUS_CODE
WHERE
A.AREA_CODE = '${AREA_CODE}'
AND
TO_CHAR(A.CUS_CODE) = '${CUS}'

--1=1
--${if(len(CUS)=0,"", "and A.CUS_CODE in ('"+CUS+"')")} 
--${if(len(AREA_CODE)=0,"", "and A.AREA_CODE in ('"+AREA_CODE+"')")}
--AND
--SALE_DATE <= DATE'${DATE1}'

and A.SALE_DATE=ss.DDATE
and 
ss.YEAR_ID = SUBSTR('${DATE1}',1,4)
GROUP BY
SALE_DATE 
ORDER BY 
SALE_DATE

SELECT 
SALE_DATE AS 日期,
ROUND(SUM(NO_TAX_AMOUNT),2) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本,
SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST) AS 无税毛利额,
SUM(SALE_QTY) AS 销售数量
FROM 
DM_SALE_TMP a,DIM_DAY b
WHERE 
AREA_CODE = '${AREA_CODE}'
AND
CUS_CODE = '${CUS}'
--1=1
--${if(len(CUS)=0,"", "and CUS_CODE in ('"+CUS+"')")} 
--${if(len(AREA_CODE)=0,"", "and AREA_CODE in ('"+AREA_CODE+"')")} 
and a.SALE_DATE=b.DDATE
AND 
b.YEAR_ID= SUBSTR('${DATE1}',1,4)-1

GROUP BY SALE_DATE

SELECT 
--A.CUS_CODE,
SALE_DATE,
SUM(A.TRAN_NUM) AS 交易笔次
FROM 
DIM_DAY ss,DM_TRANSACTION A
LEFT JOIN 
DIM_CUS B
ON 
A.AREA_CODE = B.AREA_CODE 
AND 
TO_CHAR(A.CUS_CODE) = b.CUS_CODE 
WHERE
A.AREA_CODE = '${AREA_CODE}'
AND
TO_CHAR(A.CUS_CODE) = '${CUS}'
--1=1
--${if(len(CUS)=0,"", "and A.CUS_CODE in ('"+CUS+"')")} 
--${if(len(AREA_CODE)=0,"", "and A.AREA_CODE in ('"+AREA_CODE+"')")}
--AND
--SALE_DATE <= DATE'${DATE1}'

and  
A.SALE_DATE=ss.DDATE 
and  
ss.YEAR_ID = SUBSTR('${DATE1}',1,4)-1
GROUP BY
SALE_DATE 
ORDER BY 
SALE_DATE

SELECT DISTINCT
DDATE AS 日期, 
WEEK_ID AS 第几周,
MONTH_ID||WEEK_ID as NEW_ID,
WEEK_DESC AS 星期几,
YEAR_ID AS 年份,
MONTH_ID AS 月份,
TO_CHAR(DDATE,'MM-dd') AS 日月日期
FROM DIM_DAY 
WHERE 
YEAR_ID = TO_CHAR(DATE'${DATE1}','YYYY')
AND 
DDATE <= (select max(DDATE) from DIM_DAY where  YEAR_ID = TO_CHAR(DATE'${DATE1}','YYYY') 
and WEEK_ID=(select WEEK_ID from DIM_DAY where DDATE=to_date('${DATE1}','YYYY-MM-DD')))
ORDER BY DDATE


