select DISTINCT ORGCODE,CATN,a.BUYERAREANAME AREANAME2,AREANAME 
from V_MASTERSHIP a 
where a.ORGCODE IN (SELECT DISTINCT HOSCODE FROM DEVEL_PLAN@FR_LINK)
ORDER BY ORGCODE,CATN

SELECT * FROM (

SELECT
	ID,
	HOSCODE,
	HOSNAME,
	REGIONNAME,
	CITYNAME,
	D.VALUENAME HOSGRADE,
	C.VALUENAME HOSTYPE,
	E.VALUENAME SALETYPE,
	F.VALUENAME HOSLEVEL,
	CATN,
	USERID,
	USERNAME,
	PALNTIME,
	FEE,
	REWARD,
	CREATTIME,
	YEAR,
--	TO_CHAR ( CREATTIME, 'YYYY' ) YEAR,
--	TO_CHAR ( CREATTIME, 'q' ) SEASON,
	USER1,
	FEES,
	REWARDS,
	REACH,
	RESULT,
	REMARK,
	FLAG,
	USERS,
	MODTIME 
FROM
	DEVEL_PLAN A
	INNER JOIN ORGANIZATION B ON A.HOSCODE = B.ORGCODE 
	AND GlobalPCCode = 113
	LEFT JOIN DICTIONARY C ON C.VALUE= B.customerproperty  
	AND C.type = 'HospitalProperty' 
	AND C.languagecode = 'cn'
	LEFT JOIN DICTIONARY D ON D.VALUE= B.ATTR33 
	AND D.type = 'HospitalGrade' 
	AND D.languagecode = 'cn'
	LEFT JOIN DICTIONARY E ON E.VALUE= B.CMGRP1 
	AND E.type = 'HospitalCategory' 
	AND E.languagecode = 'cn' 
	LEFT JOIN DICTIONARY F ON F.VALUE= B.hospitallevel 
	AND F.type = 'HospitalLevel' 
	AND F.languagecode = 'cn'
	LEFT JOIN REGION ON REGION.REGIONCODE=B.REGIONCODE
	LEFT JOIN CITY ON CITY.CITYCODE=B.CITYCODE
WHERE 1=1
${IF(LEN(YEAR)=0,"","AND YEAR ='"+YEAR+"'")}
--${if(len(REGIONNAME) == 0,"","and REGIONNAME in ('" + REGIONNAME + "')")}
${IF(LEN(ORG)=0,"","AND HOSCODE='"+ORG+"'")}
${IF(LEN(CATN)=0,"","AND CATN='"+CATN+"'")}
--大区采用数据集过滤形式筛选
${IF(LEN(FLAG)=0,"","AND FLAG ='"+FLAG+"'")}
${if(qwe='全国',""," and REGION.REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}
)
WHERE 1=1
${if(len(REGIONNAME) == 0,"","and REGIONNAME in ('" + REGIONNAME + "')")}

SELECT HOSCODE,HOSNAME FROM DEVEL_PLAN

SELECT MIN(TO_CHAR(DEVELTIME,'YYYY-MM')) SDATE,HOSCODE,CATN FROM DEVEL_FINISH
--WHERE ISINSERT='YES'
GROUP BY HOSCODE,CATN

SELECT  A.REGIONNAME FROM REGION A
WHERE  A.REGIONNAME NOT IN ('台湾省','香港特区','澳门特区','河北唐秦','全国')
${if(len(PROVINCE) == 0,"","and REGIONNAME in ('" + PROVINCE + "')")}

