SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.01',
                                                 'C',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.02',
                                                 'C',
                                                 '${ISNAACCOUNT}')) BUILDING_BEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1601.01.01.03',
                                                'C',
                                                '${ISNAACCOUNT}') DEVICE_BEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1601.01.01.04',
                                                'C',
                                                '${ISNAACCOUNT}') TRANSPORTATION_BEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1601.01.01.05',
                                                'C',
                                                '${ISNAACCOUNT}') EQUIPMENT_BEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1601.01.01.06',
                                                'C',
                                                '${ISNAACCOUNT}') OTHERS_BEGIN
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.01',
                                                 'DC',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.02',
                                                 'DC',
                                                 '${ISNAACCOUNT}')) BUILDING_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1602.01.01.03',
                                                'DC',
                                                '${ISNAACCOUNT}') DEVICE_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1602.01.01.04',
                                                'DC',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1602.01.01.05',
                                                'DC',
                                                '${ISNAACCOUNT}') EQUIPMENT_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1602.01.01.06',
                                                'DC',
                                                '${ISNAACCOUNT}') OTHERS_DBEGIN
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.01',
                                                 'DC',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.02',
                                                 'DC',
                                                 '${ISNAACCOUNT}')) BUILDING_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1603.01.01.03',
                                                'DC',
                                                '${ISNAACCOUNT}') DEVICE_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1603.01.01.04',
                                                'DC',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1603.01.01.05',
                                                'DC',
                                                '${ISNAACCOUNT}') EQUIPMENT_DBEGIN,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}', 0, 4) ||
                                                '-01',
                                                '${CURRENCYID}',
                                                '1603.01.01.06',
                                                'DC',
                                                '${ISNAACCOUNT}') OTHERS_DBEGIN
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.01',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.02',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) BUILDING_CNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.03',
                                                'JL',
                                                '${ISNAACCOUNT}') DEVICE_CNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.04',
                                                'JL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_CNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.05',
                                                'JL',
                                                '${ISNAACCOUNT}') EQUIPMENT_CNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.06',
                                                'JL',
                                                '${ISNAACCOUNT}') OTHERS_CNOW
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.01',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.02',
                                                 'DL',
                                                 '${ISNAACCOUNT}')) BUILDING_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.03',
                                                'DL',
                                                '${ISNAACCOUNT}') DEVICE_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.04',
                                                'DL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.05',
                                                'DL',
                                                '${ISNAACCOUNT}') EQUIPMENT_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.06',
                                                'DL',
                                                '${ISNAACCOUNT}') OTHERS_DNOW
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.01',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.02',
                                                 'DL',
                                                 '${ISNAACCOUNT}')) BUILDING_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.03',
                                                'DL',
                                                '${ISNAACCOUNT}') DEVICE_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.04',
                                                'DL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.05',
                                                'DL',
                                                '${ISNAACCOUNT}') EQUIPMENT_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.06',
                                                'DL',
                                                '${ISNAACCOUNT}') OTHERS_DNOW
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.01',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1601.01.01.02',
                                                 'DL',
                                                 '${ISNAACCOUNT}')) BUILDING_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.03',
                                                'DL',
                                                '${ISNAACCOUNT}') DEVICE_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.04',
                                                'DL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.05',
                                                'DL',
                                                '${ISNAACCOUNT}') EQUIPMENT_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1601.01.01.06',
                                                'DL',
                                                '${ISNAACCOUNT}') OTHERS_DNOW
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.01',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1602.01.01.02',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) BUILDING_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.03',
                                                'JL',
                                                '${ISNAACCOUNT}') DEVICE_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.04',
                                                'JL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.05',
                                                'JL',
                                                '${ISNAACCOUNT}') EQUIPMENT_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1602.01.01.06',
                                                'JL',
                                                '${ISNAACCOUNT}') OTHERS_DNOW
  FROM DUAL


SELECT (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.01',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '1603.01.01.02',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) BUILDING_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.03',
                                                'JL',
                                                '${ISNAACCOUNT}') DEVICE_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.04',
                                                'JL',
                                                '${ISNAACCOUNT}') TRANSPORTATION_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.05',
                                                'JL',
                                                '${ISNAACCOUNT}') EQUIPMENT_DNOW,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '1603.01.01.06',
                                                'JL',
                                                '${ISNAACCOUNT}') OTHERS_DNOW
  FROM DUAL


select '编制单位：'||name bzdw from sa_oporg where id='${organId}'

