SELECT DISTINCT 
AREA_CODE,
AREA_NAME 
FROM 
DIM_REGION

SELECT 
DISTINCT 
AGE_STORE
 FROM  
AGE_STORE

WITH AA AS 
(
SELECT 
区域编码,
客户编码,
COUNT(DISTINCT 商品编码) AS SKU,
SUM(无税销售额) AS 无税销售额,
SUM(毛利额) AS 毛利额,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END AS  是否高毛  
FROM 
(
SELECT 
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额，
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_MARKETING DD,FACT_SALE MM

LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.SALE_DATE >= DATE'${DATE1}'
AND 
MM.SALE_DATE <= DATE'${DATE2}'
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE
AND
1=1
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE


)
GROUP BY
区域编码,
客户编码,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END
) ,
A AS 
(
SELECT  
区域编码,
客户编码,
SKU AS 高毛SKU,
无税销售额 AS 高毛销售额,
毛利额 AS 高毛毛利额
FROM 
AA
WHERE  
是否高毛 = '1'
),
B AS 
(
SELECT  
区域编码,
客户编码,
SUM(SKU) AS 总体SKU,
SUM(无税销售额) AS 总体销售额,
SUM(毛利额) AS 总体毛利额
FROM 
AA
WHERE  
是否高毛 IN ('1','0')
GROUP BY 
区域编码,
客户编码
)

SELECT  
A.区域编码,
A.客户编码,
C.AREA_NAME,
D.CUS_NAME,
A.高毛SKU,
A.高毛销售额,
A.高毛毛利额,
B.总体SKU,
B.总体销售额,
B.总体毛利额
FROM 
A,B,DIM_CUS D,
DIM_REGION C
WHERE 
A.区域编码 = C.AREA_CODE
AND 
A.区域编码 = B.区域编码
AND
A.客户编码 = B.客户编码
AND
A.区域编码 = D.AREA_CODE
AND
A.客户编码 = D.CUS_CODE
${if(len(ATTRIBUTE)=0,""," and D.ATTRIBUTE IN ('"+ATTRIBUTE+"') ")}
order by C.AREA_NAME,
D.CUS_NAME

WITH AA AS 
(
SELECT 
区域编码,
客户编码,
COUNT(DISTINCT 商品编码) AS SKU,
SUM(无税销售额) AS 无税销售额,
SUM(毛利额) AS 毛利额,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END AS  是否高毛  
FROM 
(
SELECT 
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额，
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_MARKETING DD,FACT_SALE MM

LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-1)
AND 
MM.SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-1)
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE
AND
1=1
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE


)
GROUP BY
区域编码,
客户编码,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END
) ,
A AS 
(
SELECT  
区域编码,
客户编码,
SKU AS 高毛SKU,
无税销售额 AS 高毛销售额,
毛利额 AS 高毛毛利额
FROM 
AA
WHERE  
是否高毛 = '1'
),
B AS 
(
SELECT  
区域编码,
客户编码,
SUM(SKU) AS 总体SKU,
SUM(无税销售额) AS 总体销售额,
SUM(毛利额) AS 总体毛利额
FROM 
AA
WHERE  
是否高毛 IN ('1','0')
GROUP BY 
区域编码,
客户编码
)

SELECT  
A.区域编码,
A.客户编码,
A.高毛SKU,
A.高毛销售额,
A.高毛毛利额,
B.总体SKU,
B.总体销售额,
B.总体毛利额
FROM 
A,B,DIM_CUS D
WHERE 
A.客户编码 = B.客户编码
AND 
A.区域编码 = B.区域编码
and 
A.客户编码 = D.CUS_CODE
AND 
A.区域编码 = D.AREA_CODE
${if(len(ATTRIBUTE)=0,""," and D.ATTRIBUTE IN ('"+ATTRIBUTE+"') ")}



WITH AA AS 
(
SELECT 
区域编码,
客户编码,
COUNT(DISTINCT 商品编码) AS SKU,
SUM(无税销售额) AS 无税销售额,
SUM(毛利额) AS 毛利额,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END AS  是否高毛  
FROM 
(
SELECT 
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额，
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_MARKETING DD,FACT_SALE MM

LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-12)
AND 
MM.SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-12)
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE
AND
1=1
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE


)
GROUP BY
区域编码,
客户编码,
CASE WHEN 
毛利率 > 0.5
THEN 1
ELSE
0
END
) ,
A AS 
(
SELECT  
区域编码,
客户编码,
SKU AS 高毛SKU,
无税销售额 AS 高毛销售额,
毛利额 AS 高毛毛利额
FROM 
AA
WHERE  
是否高毛 = '1'
),
B AS 
(
SELECT  
区域编码,
客户编码,
SUM(SKU) AS 总体SKU,
SUM(无税销售额) AS 总体销售额,
SUM(毛利额) AS 总体毛利额
FROM 
AA
WHERE  
是否高毛 IN ('1','0')
GROUP BY 
区域编码,
客户编码
)

SELECT  
A.区域编码,
A.客户编码,
A.高毛SKU,
A.高毛销售额,
A.高毛毛利额,
B.总体SKU,
B.总体销售额,
B.总体毛利额
FROM 
A,B,DIM_CUS D
WHERE 
A.客户编码 = B.客户编码
AND 
A.区域编码 = B.区域编码
and 
A.客户编码 = D.CUS_CODE
AND 
A.区域编码 = D.AREA_CODE
${if(len(ATTRIBUTE)=0,""," and D.ATTRIBUTE IN ('"+ATTRIBUTE+"') ")}


