select * from (
SELECT 
F.AREA_NAME,
G.GOODS_NAME,
G.COMMODITY_ATTRIBUTE,
G.SPECIFICATION,
G.MANUFACTURER,
H.CUS_NAME,
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(SALE_QTY) AS 销售数量,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_REGION F,DIM_GOODS G,DIM_CUS H,DIM_MARKETING DD,FACT_SALE MM

LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.AREA_CODE = H.AREA_CODE 
AND 
MM.CUS_CODE = H.CUS_CODE 
AND
MM.GOODS_CODE  = G.GOODS_CODE  
AND
MM.AREA_CODE = F.AREA_CODE
AND
MM.SALE_DATE >= DATE'${DATE1}'
AND 
MM.SALE_DATE <= DATE'${DATE2}'
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE

${if(len(ATTRIBUTE)=0,""," and H.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(CUS)=0,""," and MM.CUS_CODE IN ('"+CUS+"') ")}
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE,
F.AREA_NAME,
G.GOODS_NAME,
G.COMMODITY_ATTRIBUTE,
G.SPECIFICATION,
G.MANUFACTURER,
H.CUS_NAME
) where 毛利率>0.5
order by AREA_NAME,
GOODS_NAME

SELECT 
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(SALE_QTY) AS 销售数量,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额，
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_MARKETING DD,DIM_CUS H,
FACT_SALE MM
LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-1)
AND 
MM.SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-1)
and MM.CUS_CODE=H.CUS_CODE 

and MM.AREA_CODE=H.AREA_CODE
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE
${if(len(ATTRIBUTE)=0,""," and H.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
AND
1=1
${if(len(CUS)=0,""," and MM.CUS_CODE IN ('"+CUS+"') ")}
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE

SELECT 
MM.CUS_CODE AS 客户编码,
MM.AREA_CODE as  区域编码,
MM.GOODS_CODE AS 商品编码,
SUM(SALE_QTY) AS 销售数量,
SUM(NO_TAX_AMOUNT)  as 无税销售额,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 毛利额，
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
THEN 0
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/SUM(NO_TAX_AMOUNT) 
END
AS 毛利率

FROM 
DIM_MARKETING DD,DIM_CUS H,FACT_SALE MM

LEFT JOIN
DIM_DTP  B
ON
MM.AREA_CODE = B.AREA_CODE 
AND 
MM.GOODS_CODE = B.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(MM.SALE_DATE,-1),'YYYY-MM') = B.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL C
ON
MM.AREA_CODE = C.AREA_CODE 
AND 
MM.GOODS_CODE = C.GOODS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN
AGE_STORE E
ON 
MM.AREA_CODE=E.AREA_CODE
AND 
MM.CUS_CODE=E.CUS_CODE
AND 
TO_CHAR(MM.SALE_DATE,'YYYY-MM') = E.DATE1

WHERE  
MM.SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-12)
AND 
MM.SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-12)
AND 
MM.MARKETING_CODE=DD.MARKETING_CODE
${if(len(ATTRIBUTE)=0,""," and H.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
and MM.CUS_CODE=H.CUS_CODE and MM.AREA_CODE=H.AREA_CODE
AND
1=1
${if(len(CUS)=0,""," and MM.CUS_CODE IN ('"+CUS+"') ")}
${if(len(AREA)=0,""," and MM.AREA_CODE IN ('"+AREA+"') ")}
${if(len(AGE)=0,""," and E.AGE_STORE IN ('"+AGE+"') ")}
${if(len(DTP)=0,""," and DECODE(B.GOODS_CODE,NULL,'否','是') IN ('"+DTP+"') ")}
${if(len(OTO)=0,""," and DD.OTO IN ('"+OTO+"') ")}
${if(len(GATHER)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') IN ('"+GATHER+"') ")}
GROUP  BY
MM.AREA_CODE,
MM.GOODS_CODE,
MM.CUS_CODE

SELECT DISTINCT 
AREA_CODE,
AREA_NAME
FROM 
DIM_REGION

SELECT 
DISTINCT 
AGE_STORE
 FROM  
AGE_STORE

SELECT DISTINCT 
A.CUS_CODE,
B.CUS_NAME
FROM 
DIM_CUS B,
DM_SALE_TMP A
WHERE 
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
AND 
A.SALE_DATE >= DATE'${DATE1}'
AND 
A.SALE_DATE <= DATE'${DATE2}'

