SELECT 
a.AREA_CODE AS 区域编码,
b.AREA_NAME AS 区域名称,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END AS 月份,
ROUND(SUM(NO_TAX_AMOUNT)/10000,2) AS 无税销售额
FROM DM_PURCHASE_GROUP_BY_AREA a

LEFT JOIN
DIM_REGION b
on 
a.AREA_CODE = b.AREA_CODE

WHERE
ATTRIBUTE IN ('销售直营','销售加盟')
AND
1=1 
${if(len(SUB_CATEGORY)=0,""," and a.SUB_CATEGORY in ('"+SUB_CATEGORY+"')")}
AND
SUBSTR(a.SALE_DATE,1,4) = SUBSTR('${Month}',1,4)

${if(len(GATHER)=0,""," and a.GATHER in ('"+GATHER+"')")}
${if(len(AREA)=0,""," and a.AREA_CODE in ('"+AREA+"')")}
${if(len(DTP)=0,""," and a.DTP in ('"+DTP+"')")}
AND
RELATED_PARTY_TRNSACTION = '否'
GROUP BY 
a.AREA_CODE,
b.AREA_NAME,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END

SELECT DISTINCT SUB_CATEGORY FROM DIM_GOODS
union 
select 'NONE' from DUAL


SELECT DISTINCT
a.AREA_CODE AS 区域编码,
b.AREA_NAME AS 区域名称,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END AS 月份,
ROUND(SUM(NO_TAX_AMOUNT)/10000,2) AS 无税销售额
FROM DM_PURCHASE_GROUP_BY_AREA a

LEFT JOIN
DIM_REGION b
on 
a.AREA_CODE = b.AREA_CODE

WHERE
ATTRIBUTE IN ('销售直营','销售加盟','配送批发')
AND
RELATED_PARTY_TRNSACTION = '否'
AND
1=1 
${if(len(SUB_CATEGORY)=0,""," and a.SUB_CATEGORY in ('"+SUB_CATEGORY+"')")}
AND
SUBSTR(a.SALE_DATE,1,4) = SUBSTR('${Month}',1,4)

${if(len(GATHER)=0,""," and a.GATHER in ('"+GATHER+"')")}

${if(len(AREA)=0,""," and a.AREA_CODE in ('"+AREA+"')")}
${if(len(DTP)=0,""," and a.DTP in ('"+DTP+"')")}
GROUP BY 
a.AREA_CODE,
b.AREA_NAME,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END
ORDER BY
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END
ASC 

SELECT 
a.AREA_CODE AS 区域编码,
b.AREA_NAME AS 区域名称,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END AS 月份,
ROUND(SUM(NO_TAX_AMOUNT)/10000,2)AS 无税销售额
FROM DM_PURCHASE_GROUP_BY_AREA a

LEFT JOIN
DIM_REGION b
on 
a.AREA_CODE = b.AREA_CODE

WHERE
ATTRIBUTE = '销售直营'
AND
1=1 
${if(len(SUB_CATEGORY)=0,""," and a.SUB_CATEGORY in ('"+SUB_CATEGORY+"')")}
AND
SUBSTR(a.SALE_DATE,1,4) = SUBSTR('${Month}',1,4)
${if(len(GATHER)=0,""," and a.GATHER in ('"+GATHER+"')")}
${if(len(AREA)=0,""," and a.AREA_CODE in ('"+AREA+"')")}
${if(len(DTP)=0,""," and a.DTP in ('"+DTP+"')")}
AND
RELATED_PARTY_TRNSACTION = '否'

GROUP BY 
a.AREA_CODE,
b.AREA_NAME,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END

SELECT 
a.AREA_CODE AS 区域编码,
b.AREA_NAME AS 区域名称,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END AS 月份,
ROUND(SUM(NO_TAX_AMOUNT)/10000,2) AS 无税销售额
FROM DM_PURCHASE_GROUP_BY_AREA a

LEFT JOIN
DIM_REGION b
on 
a.AREA_CODE = b.AREA_CODE

WHERE
ATTRIBUTE = '销售加盟'
AND
1=1 
${if(len(SUB_CATEGORY)=0,""," and a.SUB_CATEGORY in ('"+SUB_CATEGORY+"')")}
AND SUBSTR(a.SALE_DATE,1,4) = SUBSTR('${Month}',1,4)
${if(len(GATHER)=0,""," and a.GATHER in ('"+GATHER+"')")}
${if(len(AREA)=0,""," and a.AREA_CODE in ('"+AREA+"')")}
${if(len(DTP)=0,""," and a.DTP in ('"+DTP+"')")}
AND RELATED_PARTY_TRNSACTION = '否'

GROUP BY 
a.AREA_CODE,
b.AREA_NAME,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END

SELECT 
a.AREA_CODE AS 区域编码,
b.AREA_NAME AS 区域名称,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END AS 月份,
ROUND(SUM(NO_TAX_AMOUNT)/10000,2) AS 无税销售额
FROM DM_PURCHASE_GROUP_BY_AREA a
LEFT JOIN
DIM_REGION b
on 
a.AREA_CODE = b.AREA_CODE
WHERE
ATTRIBUTE = '配送批发'
AND RELATED_PARTY_TRNSACTION = '否'
AND 1=1 
${if(len(SUB_CATEGORY)=0,""," and a.SUB_CATEGORY in ('"+SUB_CATEGORY+"')")}
AND SUBSTR(a.SALE_DATE,1,4) = SUBSTR('${Month}',1,4)
${if(len(GATHER)=0,""," and a.GATHER in ('"+GATHER+"')")}
${if(len(AREA)=0,""," and a.AREA_CODE in ('"+AREA+"')")}
${if(len(DTP)=0,""," and a.DTP in ('"+DTP+"')")}
GROUP BY 
a.AREA_CODE,
b.AREA_NAME,
CASE WHEN
SUBSTr(SALE_DATE,6,7) < '10'
AND  
SUBSTr(SALE_DATE,6,7)  >= '01'
THEN
CONCAT(SUBSTr(SALE_DATE,7,7),'月') 
ELSE
CONCAT(SUBSTr(SALE_DATE,6,7),'月')
END

select distinct YEAR_ID from DIM_DAY order by YEAR_ID   asc

SELECT
'1月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'2月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'3月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'4月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'5月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'6月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'7月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'8月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'9月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'10月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'11月'  AS 月份
FROM DUAL
UNION ALL
SELECT
'12月'  AS 月份
FROM DUAL

SELECT DISTINCT UNION_AREA_NAME,AREA_CODE,AREA_NAME 
FROM 
DIM_REGION
WHERE 
1=1
${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}
order by AREA_CODE asc

SELECT DISTINCT GATHER
FROM 
DM_PURCHASE_GROUP_BY_AREA 



SELECT 
DISTINCT 
AREA_CODE AS 区域编码, 
AREA_NAME AS 区域名称,
UNION_AREA_NAME
FROM DIM_REGION
WHERE 
1=1
${if(len(UNION_AREA)=0,""," and UNION_AREA_NAME in ('"+UNION_AREA+"')")}


SELECT  DISTINCT  
UNION_AREA_NAME
FROM 
DIM_REGION

