SELECT * FROM (

SELECT
	ID,
	TO_CHAR( DEVELTIME, 'YYYY' ) YEAR,
	TO_CHAR( DEVELTIME, 'MM' ) MONTH,
	H.AREANAME AREANAME1,
	I.AREANAME AREANAME2,
	REGIONNAME,
	CITYNAME,
	HOSCODE,
	HOSNAME,
	D.VALUENAME HOSGRADE,
	C.VALUENAME HOSTYPE,
	E.VALUENAME SALETYPE,
	CASE WHEN F.VALUENAME IN ('三甲','三乙','三丙') and customerproperty in(1,2,3,4,6,7) THEN '三级'
	WHEN F.VALUENAME IN ('二甲','二乙','二丙') and customerproperty in(1,2,3,4,6,7) THEN '二级'
	WHEN F.VALUENAME IN ('一甲','一乙','一丙') OR F.VALUENAME IS NULL or customerproperty in(5,8,9,10,11) THEN '基层' 
	ELSE '其他' END  HOSLEVEL,
	A.CATN,
	P.PRDPD,
	FEE,
	REWARD,
	ISINSERT,
	REMARK,
	CREATTIME
FROM
	DEVEL_FINISH A 
	INNER JOIN ORGANIZATION B ON A.HOSCODE = B.ORGCODE 
	AND GlobalPCCode = 113 
	LEFT JOIN PRODUCT p ON A.PRODCODE=p.PRODCODE
	LEFT JOIN MASTERSHIP@CMILINK G ON G.ORGID=B.ORGID AND p.prdpd=G.prdpd
	LEFT JOIN BUSINESSAREA H ON G.BUSINESSAREAID=H.AREAID
	LEFT JOIN BUSINESSAREA I ON H.PARENTAREAID=I.AREAID
	LEFT JOIN DICTIONARY C ON C.VALUE = B.customerproperty  
	AND C.TYPE = 'HospitalProperty' 
	AND C.languagecode = 'cn' 
	LEFT JOIN DICTIONARY D ON D.VALUE = B.ATTR33 
	AND D.TYPE = 'HospitalGrade' 
	AND D.languagecode = 'cn' 
	LEFT JOIN DICTIONARY E ON E.VALUE = B.CMGRP1 
	AND E.TYPE = 'HospitalCategory' 
	AND E.languagecode = 'cn' 
	LEFT JOIN DICTIONARY F ON F.VALUE = B.hospitallevel 
	AND F.TYPE = 'HospitalLevel' 
	AND F.languagecode = 'cn' 
	LEFT JOIN REGION ON REGION.REGIONCODE = B.REGIONCODE 
	LEFT JOIN CITY ON CITY.CITYCODE = B.CITYCODE
WHERE 1=1
${IF(LEN(YEAR)=0,"","AND TO_CHAR ( DEVELTIME, 'YYYY' )='"+YEAR+"'")}
${IF(LEN(MONTH)=0,"","AND TO_NUMBER(TO_CHAR ( DEVELTIME, 'MM' ))='"+MONTH+"'")}
${IF(LEN(AREA)=0,"","AND I.AREANAME='"+AREA+"'")}
--${IF(LEN(PROV)=0,"","AND REGIONNAME='"+PROV+"'")}
${IF(LEN(CUSTOM)=0,"","AND HOSCODE ='"+CUSTOM+"'")}
${IF(LEN(CATN)=0,"","AND p.CATN IN ('"+SUBSTITUTE(CATN,",","','")+"')")}
${IF(LEN(PRDPD)=0,"","AND p.PRDPD IN ('"+SUBSTITUTE(PRDPD,",","','")+"')")}
${IF(LEN(ISNOT)=0,"","AND ISINSERT ='"+ISNOT+"'")}
${if(qwe='全国',""," and REGION.REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}
ORDER BY DEVELTIME,HOSCODE)
WHERE 1=1
${IF(LEN(PROV)=0,"","AND REGIONNAME ='"+PROV+"'")}

SELECT DISTINCT B.AREAID,B.AREANAME FROM BUSINESSAREA A
INNER JOIN BUSINESSAREA B ON A.PARENTAREAID=B.AREAID

SELECT REGIONNAME FROM REGION A
WHERE 1=1
${if(qwe='全国',""," and A.REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}
ORDER BY REGIONID


SELECT DISTINCT HOSCODE,HOSNAME FROM DEVEL_FINISH

SELECT * FROM PRODUCT
ORDER BY PRODCODE

