SELECT A.COST_CENTER_ID,
       A.COST_CENTER_NAME,
       A.COST_ITEM_ID,
       B.COST_ITEM_NAME,
       B.LEV,
       B.SERIALNO,
       NVL(B.PARENT_ID, A.COST_ITEM_ID) PARENT_ID,
       NVL(C.COST_ITEM_NAME, A.COST_ITEM_NAME) COST_COST_ITEM_NAME,
       SUM(A.MFC_TOTAL) OVER(PARTITION BY A.COST_ITEM_ID, A.COST_ITEM_NAME, B.PARENT_ID, A.COST_CENTER_ID, A.COST_CENTER_NAME) TWO_LEV_MOUNT,
       SUM(A.MFC_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.COST_CENTER_ID) ONE_LEV_AMOUT,
       SUM(A.RD_TOTAL) OVER(PARTITION BY A.COST_ITEM_ID, A.COST_ITEM_NAME, B.PARENT_ID, A.COST_CENTER_ID, A.COST_CENTER_NAME) TWO_LEV_MOUNT1,
       SUM(A.RD_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.COST_CENTER_ID) ONE_LEV_AMOUT1,
       SUM(A.MAKE_TOTAL) OVER(PARTITION BY A.COST_ITEM_ID, A.COST_ITEM_NAME, B.PARENT_ID, A.COST_CENTER_ID, A.COST_CENTER_NAME) TWO_LEV_MOUNT2,
       SUM(A.MAKE_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.COST_CENTER_ID) ONE_LEV_AMOUT2,
       SUM(A.MANAGE_TOTAL) OVER(PARTITION BY A.COST_ITEM_ID, A.COST_ITEM_NAME, B.PARENT_ID, A.COST_CENTER_ID, A.COST_CENTER_NAME) TWO_LEV_MOUNT3,
       SUM(A.MANAGE_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.COST_CENTER_ID) ONE_LEV_AMOUT3
  FROM VIEW_FN_REVERT_DATA           A,
       VIEW_FN_COST_REVERT_COST_ITEM B,
       VIEW_FN_COST_REVERT_COST_ITEM C,
       COM_FNORG                     O
 WHERE A.COST_ITEM_ID = B.ID
   AND B.PARENT_ID = C.ID(+)
   AND A.YEAR_MONTH_V >= '${yearmonthBegin}'
   AND A.YEAR_MONTH_V <= '${yearmonthEnd}'
   AND A.ORGAN_ID = '${organId}'
   AND A.COST_CENTER_ID = O.ID
 ORDER BY NVL(C.SERIALNO,B.SERIALNO),B.SERIALNO, O.ORGCODE ASC

