SELECT A.FN_ORG_ID,
       A.FN_ORG_NAME,
       A.ITAM_ID,
       A.ITEM_NAME,
       B.LEV,
	  B.SERIALNO,       
       NVL(B.PARENT_ID, A.ITAM_ID) PARENT_ID,
       NVL(C.COST_ITEM_NAME, A.ITEM_NAME) COST_ITEM_NAME,
       SUM(A.MFC_TOTAL) OVER(PARTITION BY A.ITAM_ID, A.ITEM_NAME, B.PARENT_ID, A.FN_ORG_ID, A.FN_ORG_NAME) TWO_LEV_MOUNT,
       SUM(A.MFC_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.FN_ORG_ID) ONE_LEV_AMOUT,
       SUM(A.RD_TOTAL) OVER(PARTITION BY A.ITAM_ID, A.ITEM_NAME, B.PARENT_ID, A.FN_ORG_ID, A.FN_ORG_NAME) TWO_LEV_MOUNT1,
       SUM(A.RD_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.FN_ORG_ID) ONE_LEV_AMOUT1,
       SUM(A.MAKE_TOTAL) OVER(PARTITION BY A.ITAM_ID, A.ITEM_NAME, B.PARENT_ID, A.FN_ORG_ID, A.FN_ORG_NAME) TWO_LEV_MOUNT2,
       SUM(A.MAKE_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.FN_ORG_ID) ONE_LEV_AMOUT2,
       SUM(A.MANAGE_TOTAL) OVER(PARTITION BY A.ITAM_ID, A.ITEM_NAME, B.PARENT_ID, A.FN_ORG_ID, A.FN_ORG_NAME) TWO_LEV_MOUNT3,
       SUM(A.MANAGE_TOTAL) OVER(PARTITION BY B.PARENT_ID, A.FN_ORG_ID) ONE_LEV_AMOUT3
  FROM FN_COST_REVERT_MFC_DATA       A,
       VIEW_FN_COST_REVERT_COST_ITEM B,
       VIEW_FN_COST_REVERT_COST_ITEM C
 WHERE A.ITAM_ID = B.ID
   AND B.PARENT_ID = C.ID(+)
   AND A.YEARMONTH_V >= '${yearmonthBegin}'
   AND A.YEARMONTH_V <= '${yearmonthEnd}'
   AND A.ORGAN_ID = '${organId}'
   ORDER BY NVL(C.SERIALNO,B.SERIALNO),B.SERIALNO,A.FN_ORG_NAME ASC

