SELECT (SELECT ROUND(SUM(T.NORMAL_W) / 1000000, 8)
          FROM FN_COST_PDT_IN T
         WHERE T.YEAR_MONTH_V = '${YEARMONTH}'
           AND T.ORGAN_ID = '${ORGANID}'
           AND T.PRODUCT_CATEGORY = '1'
           AND (T.NORMAL_YL != 0 OR T.NORMAL_FL != 0 OR T.NORMAL_BZ != 0 OR
               T.NORMAL_RG != 0)) QTY1,
       (SELECT ROUND(SUM(T.NORMAL_W) / 1000000, 8)
          FROM FN_COST_PDT_IN T
         WHERE T.YEAR_MONTH_V = '${YEARMONTH}'
           AND T.ORGAN_ID = '${ORGANID}'
           AND T.PRODUCT_CATEGORY = '2'
           AND (T.NORMAL_BZ != 0 OR T.NORMAL_RG != 0)) QTY2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6001',
                                                'QDFC',
                                                '${ISNAACCOUNT}') / 1000000 QTY3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6001',
                                                'QDFM',
                                                '${ISNAACCOUNT}') / 1000000 QTY4
  FROM DUAL


SELECT DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6401',
                                                    'JF',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}') * 100) QTY1,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6601',
                                                    'JF',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}') * 100) QTY2,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                     '${YEARMONTH}',
                                                     '${CURRENCYID}',
                                                     '6602',
                                                     'JF',
                                                     '${ISNAACCOUNT}') -
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                     '${YEARMONTH}',
                                                     '${CURRENCYID}',
                                                     '6602.30',
                                                     'JF',
                                                     '${ISNAACCOUNT}')) /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}') * 100) QTY3,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6603',
                                                    'JF',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}') * 100) QTY4,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6602.30',
                                                    'JF',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DF',
                                                    '${ISNAACCOUNT}') * 100) QTY5
  FROM DUAL


SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6001',
                                             'DF',
                                             '${ISNAACCOUNT}') / 10000 QTY1,
       ((SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                               '${YEARMONTH}',
                                               '${CURRENCYID}',
                                               '6001',
                                               'DF',
                                               '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                               '${YEARMONTH}',
                                               '${CURRENCYID}',
                                               '6051',
                                               'DF',
                                               '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                               '${YEARMONTH}',
                                               '${CURRENCYID}',
                                               '6112',
                                               'DF',
                                               '${ISNAACCOUNT}')) -
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                               '${YEARMONTH}',
                                               '${CURRENCYID}',
                                               '6401',
                                               'JF',
                                               '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                               '${YEARMONTH}',
                                               '${CURRENCYID}',
                                               '6402',
                                               'JF',
                                               '${ISNAACCOUNT}')) -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6403',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6601',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6602',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6603',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6701',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6702',
                                              'JF',
                                              '${ISNAACCOUNT}') +                                              
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6101',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6111',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6301',
                                              'DF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6711',
                                              'JF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6113',
                                              'DF',
                                              '${ISNAACCOUNT}')) / 10000 QTY2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6401',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6601',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY4,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6602',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6602.30',
                                              'JF',
                                              '${ISNAACCOUNT}')) / 10000 QTY5,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6603',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY6,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6051',
                                             'DF',
                                             '${ISNAACCOUNT}') / 10000 QTY7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6402',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6602.30',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY9,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6001',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6051',
                                              'DF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6401',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6402',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6403',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6601',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6602',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6603',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6701',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6702',
                                              'JF',
                                              '${ISNAACCOUNT}') +                                              
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6112',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6111',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6101',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6113',
                                              'DF',
                                              '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6301',
                                              'DF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6711',
                                              'JF',
                                              '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                              '${YEARMONTH}',
                                              '${CURRENCYID}',
                                              '6801',
                                              'JF',
                                              '${ISNAACCOUNT}')) / 10000 QTY10,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6403',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY11,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6702',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY12,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6111',
                                             'DF',
                                             '${ISNAACCOUNT}') / 10000 QTY13,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6113',
                                             'DF',
                                             '${ISNAACCOUNT}') / 10000 QTY14,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6301',
                                             'DF',
                                             '${ISNAACCOUNT}') / 10000 QTY15,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6711',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY16,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6801',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY17,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                             '${YEARMONTH}',
                                             '${CURRENCYID}',
                                             '6112',
                                             'JF',
                                             '${ISNAACCOUNT}') / 10000 QTY18
  FROM DUAL

SELECT DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6401',
                                                    'JL',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}') * 100) QTY1,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6601',
                                                    'JL',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}') * 100) QTY2,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                     '${YEARMONTH}',
                                                     '${CURRENCYID}',
                                                     '6602',
                                                     'JL',
                                                     '${ISNAACCOUNT}') -
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                     '${YEARMONTH}',
                                                     '${CURRENCYID}',
                                                     '6602.30',
                                                     'JL',
                                                     '${ISNAACCOUNT}')) /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}') * 100) QTY3,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6603',
                                                    'JL',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}') * 100) QTY4,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}'),
              0,
              NULL,
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6602.30',
                                                    'JL',
                                                    '${ISNAACCOUNT}') /
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                    '${YEARMONTH}',
                                                    '${CURRENCYID}',
                                                    '6001',
                                                    'DL',
                                                    '${ISNAACCOUNT}') * 100) QTY6
  FROM DUAL


SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6001',
                                                'DL',
                                                '${ISNAACCOUNT}') / 10000 QTY1,
       ((SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                  '${YEARMONTH}',
                                                  '${CURRENCYID}',
                                                  '6001',
                                                  'DL',
                                                  '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                  '${YEARMONTH}',
                                                  '${CURRENCYID}',
                                                  '6051',
                                                  'DL',
                                                  '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                  '${YEARMONTH}',
                                                  '${CURRENCYID}',
                                                  '6112',
                                                  'DL',
                                                  '${ISNAACCOUNT}')) -
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                  '${YEARMONTH}',
                                                  '${CURRENCYID}',
                                                  '6401',
                                                  'JL',
                                                  '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                  '${YEARMONTH}',
                                                  '${CURRENCYID}',
                                                  '6402',
                                                  'JL',
                                                  '${ISNAACCOUNT}')) -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6403',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6601',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6602',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6603',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6701',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6702',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +                                                 
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6101',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6111',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6301',
                                                 'DL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6711',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6113',
                                                 'DL',
                                                 '${ISNAACCOUNT}')) / 10000 QTY2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6401',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6601',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY4,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6602',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6602.30',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) / 10000 QTY5,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6603',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY6,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6051',
                                                'DL',
                                                '${ISNAACCOUNT}') / 10000 QTY7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6402',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6602.30',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY9,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6001',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6051',
                                                 'DL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6401',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6402',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6403',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6601',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6602',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6603',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6701',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6702',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +                                                 
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6112',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6111',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6101',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6113',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6301',
                                                 'DL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6711',
                                                 'JL',
                                                 '${ISNAACCOUNT}') -
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '6801',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) / 10000 QTY10,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6403',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY11,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6702',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY12,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6111',
                                                'DL',
                                                '${ISNAACCOUNT}') / 10000 QTY13,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6113',
                                                'DL',
                                                '${ISNAACCOUNT}') / 10000 QTY14,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6301',
                                                'DL',
                                                '${ISNAACCOUNT}') / 10000 QTY15,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6711',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY16,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6801',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY17,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6112',
                                                'JL',
                                                '${ISNAACCOUNT}') / 10000 QTY18
  FROM DUAL

SELECT (SELECT ROUND(SUM(T.NORMAL_W) / 1000000, 8) NORMAL_W
          FROM FN_COST_PDT_IN T
         WHERE T.YEAR_MONTH_V <= '${YEARMONTH}'
           AND T.ORGAN_ID = '${ORGANID}'
           AND T.PRODUCT_CATEGORY = '1'
           AND (T.NORMAL_YL != 0 OR T.NORMAL_FL != 0 OR T.NORMAL_BZ != 0 OR
               T.NORMAL_RG != 0)) QTY1,
       (SELECT ROUND(SUM(T.NORMAL_W) / 1000000, 8) NORMAL_W
          FROM FN_COST_PDT_IN T
         WHERE T.YEAR_MONTH_V <= '${YEARMONTH}'
           AND T.ORGAN_ID = '${ORGANID}'
           AND T.PRODUCT_CATEGORY = '2'
           AND (T.NORMAL_BZ != 0 OR T.NORMAL_RG != 0)) QTY2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6001',
                                                'QDLC',
                                                '${ISNAACCOUNT}') QTY3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '6001',
                                                'QDLM',
                                                '${ISNAACCOUNT}') QTY4
  FROM DUAL

select name bzdw from sa_oporg where id='${organId}'

