SELECT 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME,
--NVL(D.NEW_ATTRIBUTE,'地采') AS GATHER,
--DECODE(C.GOODS_CODE,NULL,'否','是') AS DTP,
SUM(DELIVERY_QTY) AS 配送数量,
SUM(NO_TAX_AMOUNT) AS 无税销售金额,
SUM(NO_TAX_COST) AS 无税销售成本
FROM  
DIM_REGION F,
DIM_CUS B,
DIM_GOODS E,
FACT_DELIVERY A


LEFT JOIN 
DIM_DISABLE_CODE G
ON 
A.GOODS_CODE = G.DISABLE_CODE


LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
G.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(SALE_DATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
G.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(SALE_DATE,'YYYY-MM') = D.CREATE_MONTH

WHERE 
A.AREA_CODE = F.AREA_CODE
AND
G.GOODS_CODE = E.GOODS_CODE
AND
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND
SALE_DATE >= DATE'${DATE1}'
AND 
SALE_DATE <= DATE'${DATE2}'
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and G.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP BY 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME
--DECODE(C.GOODS_CODE,NULL,'否','是'),
--NVL(D.NEW_ATTRIBUTE,'地采')

SELECT 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME,
SUM(DELIVERY_QTY) AS 配送数量,
SUM(NO_TAX_AMOUNT) AS 无税销售金额,
SUM(NO_TAX_COST) AS 无税销售成本
FROM  
DIM_REGION F,
DIM_CUS B,
DIM_GOODS E,
FACT_DELIVERY A

LEFT JOIN 
DIM_DISABLE_CODE G
ON 
A.GOODS_CODE = G.DISABLE_CODE


LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
G.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(SALE_DATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
G.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(SALE_DATE,'YYYY-MM') = D.CREATE_MONTH

WHERE 
A.AREA_CODE = F.AREA_CODE
AND
G.GOODS_CODE = E.GOODS_CODE
AND
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND
SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-1)
AND 
SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-1)
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and G.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP BY 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME

SELECT 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME,
--SALE_DATE,
--NVL(D.NEW_ATTRIBUTE,'地采') AS GATHER,
--DECODE(C.GOODS_CODE,NULL,'否','是') AS DTP,
SUM(DELIVERY_QTY) AS 配送数量,
SUM(NO_TAX_AMOUNT) AS 无税销售金额,
SUM(NO_TAX_COST) AS 无税销售成本
FROM  
DIM_REGION F,
DIM_CUS B,
DIM_GOODS E,
FACT_DELIVERY A


LEFT JOIN 
DIM_DISABLE_CODE G
ON 
A.GOODS_CODE = G.DISABLE_CODE



LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
G.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(SALE_DATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
G.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(SALE_DATE,'YYYY-MM') = D.CREATE_MONTH

WHERE 
A.AREA_CODE = F.AREA_CODE
AND
G.GOODS_CODE = E.GOODS_CODE
AND
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND
SALE_DATE >= ADD_MONTHS(DATE'${DATE1}',-12)
AND 
SALE_DATE <= ADD_MONTHS(DATE'${DATE2}',-12)
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and G.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP BY 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME

SELECT DISTINCT 
AREA_CODE,
AREA_NAME
FROM 
DIM_REGION 


SELECT  DISTINCT 
A.CUS_CODE,
B.CUS_NAME
FROM 
FACT_DELIVERY A
,
DIM_CUS B 
WHERE 
A.CUS_CODE = B.CUS_CODE 
AND 
A.SALE_DATE >= DATE'${DATE1}'
AND
A.SALE_DATE <= DATE'${DATE2}'
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}

SELECT DISTINCT 
D.GOODS_CODE,
B.GOODS_NAME,
D.GOODS_CODE||'|'||B.GOODS_NAME
FROM
DIM_GOODS B, 
FACT_DELIVERY A

LEFT JOIN 
DIM_DISABLE_CODE D
ON 
A.GOODS_CODE = D.DISABLE_CODE

WHERE 
D.GOODS_CODE = B.GOODS_CODE 
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
AND 
A.SALE_DATE >= DATE'${DATE1}'
AND
A.SALE_DATE <= DATE'${DATE2}'
order by d.goods_code

SELECT  DISTINCT NEW_ATTRIBUTE
FROM 
DIM_NET_CATALOGUE_GENERAL_ALL

UNION ALL

SELECT '地采' FROM DUAL

SELECT 
DISTINCT 
ATTRIBUTE
FROM
DIM_CUS
WHERE 
ATTRIBUTE  IN ('直营','加盟')

SELECT 
B.GOODS_CODE,
A.AREA_CODE,
SUM(NO_TAX_COST),
SUM(STOCK_QTY)

FROM  
DIM_CUS E,
DM_STOCK_SHOP_DETAIL A

LEFT JOIN 
DIM_DISABLE_CODE B
ON 
A.GOODS_CODE = B.DISABLE_CODE

LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
B.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(DDATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
B.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(DDATE,'YYYY-MM') = D.CREATE_MONTH



WHERE 
A.CUS_CODE = E.CUS_CODE
AND 
A.AREA_CODE = E.AREA_CODE
AND
DDATE >= DATE'${DATE1}'
AND 
DDATE <= DATE'${DATE2}'
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and B.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and E.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP  bY
B.GOODS_CODE,
A.AREA_CODE

SELECT 
B.GOODS_CODE,
A.AREA_CODE,
SUM(NO_TAX_COST),
SUM(STOCK_QTY)

FROM  
DIM_CUS E,
DM_STOCK_SHOP_DETAIL A

LEFT JOIN 
DIM_DISABLE_CODE B
ON 
A.GOODS_CODE = B.DISABLE_CODE

LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
B.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(DDATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
B.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(DDATE,'YYYY-MM') = D.CREATE_MONTH



WHERE 
A.CUS_CODE = E.CUS_CODE
AND 
A.AREA_CODE = E.AREA_CODE
AND
DDATE >= ADD_MONTHS(DATE'${DATE1}',-12)
AND 
DDATE <= ADD_MONTHS(DATE'${DATE2}',-12)
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and B.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and E.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP  bY
B.GOODS_CODE,
A.AREA_CODE

SELECT 
B.GOODS_CODE,
A.AREA_CODE,
SUM(NO_TAX_COST),
SUM(STOCK_QTY)

FROM  
DIM_CUS E,
DM_STOCK_SHOP_DETAIL A

LEFT JOIN 
DIM_DISABLE_CODE B
ON 
A.GOODS_CODE = B.DISABLE_CODE

LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
B.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(DDATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
B.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(DDATE,'YYYY-MM') = D.CREATE_MONTH



WHERE 
A.CUS_CODE = E.CUS_CODE
AND 
A.AREA_CODE = E.AREA_CODE
AND
DDATE >= ADD_MONTHS(DATE'${DATE1}',-1)
AND 
DDATE <= ADD_MONTHS(DATE'${DATE2}',-1)
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and B.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and E.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

GROUP  bY
B.GOODS_CODE,
A.AREA_CODE

SELECT DISTINCT 
AREA_CODE,
AREA_NAME
FROM 
DIM_REGION 
WHERE
1=1
${if(len(AREA)=0,""," and AREA_CODE in ('"+AREA+"')")}

SELECT 
DISTINCT
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME
FROM  
DIM_REGION F,
DIM_CUS B,
DIM_GOODS E,
FACT_DELIVERY A


LEFT JOIN 
DIM_DISABLE_CODE G
ON 
A.GOODS_CODE = G.DISABLE_CODE


LEFT JOIN 
DIM_DTP C
ON 
A.AREA_CODE = C.AREA_CODE 
AND 
G.GOODS_CODE = C.GOODS_CODE 
AND 
TO_CHAR(ADD_MONTHS(SALE_DATE,-1),'YYYY-MM') = C.CREATE_MONTH

LEFT JOIN 
DIM_NET_CATALOGUE_GENERAL_ALL D
ON
A.AREA_CODE = D.AREA_CODE 
AND 
G.GOODS_CODE = D.GOODS_CODE
AND 
TO_CHAR(SALE_DATE,'YYYY-MM') = D.CREATE_MONTH

WHERE 
A.AREA_CODE = F.AREA_CODE
AND
G.GOODS_CODE = E.GOODS_CODE
AND
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND
SALE_DATE >= DATE'${DATE1}'
AND 
SALE_DATE <= DATE'${DATE2}'
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and G.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and DECODE(C.GOODS_CODE,NULL,'否','是') in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and NVL(D.NEW_ATTRIBUTE,'地采') in ('"+GATHER+"')")}

UNION


SELECT
DISTINCT 
G.GOODS_CODE,
E.GOODS_NAME,
E.MANUFACTURER,
E.SPECIFICATION,
A.AREA_CODE,
F.AREA_NAME
FROM  
DIM_REGION F,
DIM_CUS B,
DIM_GOODS E,
DM_STOCK_SHOP_DETAIL A


LEFT JOIN 
DIM_DISABLE_CODE G
ON 
A.GOODS_CODE = G.DISABLE_CODE



WHERE 
A.AREA_CODE = F.AREA_CODE
AND
G.GOODS_CODE = E.GOODS_CODE
AND
A.AREA_CODE = B.AREA_CODE 
AND 
A.CUS_CODE = B.CUS_CODE
AND
DDATE >= DATE'${DATE1}'
AND 
DDATE <= DATE'${DATE2}'
AND 
1=1
${if(len(AREA)=0,""," and A.AREA_CODE in ('"+AREA+"')")}
${if(len(GOODS)=0,""," and G.GOODS_CODE in ('"+GOODS+"')")}
${if(len(DTP)=0,""," and A.DTP in ('"+DTP+"')")}
${if(len(ATTRIBUTE)=0,""," and B.ATTRIBUTE in ('"+ATTRIBUTE+"')")}
${if(len(GATHER)=0,""," and A.GATHER in ('"+GATHER+"')")}


