SELECT DISTINCT VARIETIES FROM TABLE_STRATEGIC 
WHERE 1=1
${if(len(STRATEGICCHANNEL) == 0,"","and STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
${if(len(awe)==0,""," and VARIETIES IN ('"+SUBSTITUTE(awe,",","','")+"')")}
	ORDER BY
		VARIETIES DESC

	SELECT
	DISTINCT PRDN
FROM
	PRODUCT
	WHERE CATN  
	 in ('${CATN}') 
	 ORDER BY PRDN DESC




SELECT  A.REGIONNAME FROM REGION A
WHERE  A.REGIONNAME NOT IN ('台湾省','香港特区','澳门特区','河北唐秦','全国')
${if(len(PROVINCE) == 0,"","and REGIONNAME in ('" + PROVINCE + "')")}
${if(qwe='全国',""," and A.REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}

SELECT
	PROVINCE,
	ROUND(SUM (MONTH_PRICE),2) AS MONTH_PRICE,
  ROUND(SUM (MONTH_PRICE/UNITPRICE),4) AS MONTH_QTY
FROM
	AREANAME_TARGET_PRICE A
 LEFT JOIN  (SELECT DISTINCT PRDN,UNITPRICE FROM  PRODUCT) B
ON A.PRDN=B.PRDN
WHERE 1=1
AND FLAG='部门'
AND DEPT!='电商事业部'
${if(len(STRATEGICCHANNEL) == 0,"","and CHANNEL_TYPE in ('" + STRATEGICCHANNEL + "')")}
${if(len(DEPARTMENT) == 0,"","and A.DEPT in ('" + DEPARTMENT + "')")}	
${if(len(awe)==0,""," and A.CATN IN ('"+SUBSTITUTE(awe,",","','")+"')")}
${if(len(CATN) == 0,"","and A.CATN in ('" + CATN + "')")}
${if(len(PRDN) == 0,"","and A.PRDN in ('" + PRDN + "')")}
AND DATES=SUBSTR('${SDATE}',1,4)
AND MONTHS>=SUBSTR('${SDATE}',6,2)
AND MONTHS<=SUBSTR('${EDATE}',6,2)
${if(qwe='全国',""," and A.PROVINCE IN ('"+SUBSTITUTE(qwe,",","','")+"')")}

GROUP BY  PROVINCE

SELECT 
F.PROVINCE,
SALEPRICE,
SALEQTY,
QTY,
TOTAL_PRICE,
(SALEPRICE-TOTAL_PRICE)/DECODE(TOTAL_PRICE,0,1,TOTAL_PRICE) AS PRICE_RATE,    --同比增长
(SALEQTY-QTY)/DECODE(QTY,0,1,QTY) AS QTY_RATE

FROM
-------取今年销售数据

(SELECT DISTINCT PROVINCE FROM (
SELECT PROVINCE,STRATEGICCHANNEL FROM DW_DEPT_SALE  WHERE PROVINCE!='台湾省'
UNION
SELECT PROVINCE,STRATEGICCHANNEL FROM FILL_SALE_HISTORY F 	LEFT JOIN TABLE_STRATEGIC C   ON F.CATN=C.VARIETIES   
UNION
SELECT PROVINCE,CHANNEL_TYPE AS STRATEGICCHANNEL FROM AREANAME_TARGET_PRICE )
WHERE STRATEGICCHANNEL  IS NOT NULL
 ${if(len(STRATEGICCHANNEL) == 0,"","and STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
 ${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}
 ) F
LEFT JOIN 
(SELECT
	A.PROVINCE,
	SUM(SALEPRICE)/10000 AS SALEPRICE,
	SUM(SALEQTY)/10000 AS SALEQTY
FROM
	DW_SALE_PRICE A
	LEFT JOIN TABLE_STRATEGIC C
	ON A.CATEGORYNAME=C.VARIETIES
WHERE 1=1
     ${if(len(STRATEGICCHANNEL) == 0,"","and C.STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
     
${if(len(awe)==0,""," and CATEGORYNAME IN ('"+SUBSTITUTE(awe,",","','")+"')")}
          
	${if(len(CATN) == 0,"","and CATEGORYNAME in ('" + CATN + "')")}
	${if(len(PRDN) == 0,"","and PRDN in ('" + PRDN + "')")}
	${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}
	${if(len(DEPARTMENT) == 0,"","and DEPARTMENT in ('" + DEPARTMENT + "')")}
AND SUBSTR(POSTDATE,1,4)=SUBSTR('${SDATE}',1,4)
AND SUBSTR(POSTDATE,6,2)>=SUBSTR('${SDATE}',6,2)
AND SUBSTR(POSTDATE,1,4)=SUBSTR('${EDATE}',1,4)
AND SUBSTR(POSTDATE,6,2)<=SUBSTR('${EDATE}',6,2)
GROUP BY PROVINCE) A
ON F.PROVINCE=A.PROVINCE

LEFT JOIN 
--------------取去年数据
(SELECT
  A.PROVINCE,
  SUM(QTY) AS QTY,
  SUM(TOTAL_PRICE) AS TOTAL_PRICE
FROM
	FILL_SALE_HISTORY A
		LEFT JOIN TABLE_STRATEGIC C
	ON A.CATN=C.VARIETIES
WHERE 1=1
     AND FLAG='省份'
     ${if(len(STRATEGICCHANNEL) == 0,"","and C.STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
     ${if(len(awe)==0,""," and CATN IN ('"+SUBSTITUTE(awe,",","','")+"')")}
	${if(len(CATN) == 0,"","and CATN in ('" + CATN + "')")}
	--${if(len(PRDN) == 0,"","and PRDN in ('" + PRDN + "')")}
	${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}
	${if(len(DEPARTMENT) == 0,"","and BUYERAREANAME in ('" + DEPARTMENT + "')")}
AND MONTHS>=SUBSTR('${SDATE}',6,2)
AND YEARS=SUBSTR('${EDATE}',1,4)-1
AND MONTHS<=SUBSTR('${EDATE}',6,2)
GROUP BY PROVINCE)  B
ON F.PROVINCE=B.PROVINCE
WHERE 1=1

${if(qwe='全国',""," and F.PROVINCE IN ('"+SUBSTITUTE(qwe,",","','")+"')")}



------------------------执行进度----
SELECT
A.PROVINCE,
A.TARGET_PRICE,
B.TOTAL_PRICE,
QTY,
TARGET_QTY/10000 AS TARGET_QTY,
TOTAL_PRICE/DECODE(TARGET_PRICE,0,1,TARGET_PRICE) AS RATE,
QTY/DECODE(TARGET_QTY,0,1,TARGET_QTY) AS QTY_RATE
FROM (
   SELECT
	PROVINCE,
	ROUND(SUM (MONTH_PRICE),2) AS TARGET_PRICE,
     ROUND(SUM (MONTH_PRICE*10000/UNITPRICE),0) AS TARGET_QTY
FROM AREANAME_TARGET_PRICE A   
LEFT JOIN  
(SELECT DISTINCT PRDN, UNITPRICE FROM PRODUCT) C
ON A.PRDN=C.PRDN
WHERE FLAG='部门'
AND DEPT!='电商事业部'
${if(len(STRATEGICCHANNEL) == 0,"","and CHANNEL_TYPE in ('" + STRATEGICCHANNEL + "')")}
${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}	
${if(len(DEPARTMENT) == 0,"","and A.DEPT in ('" + DEPARTMENT + "')")}
${if(len(awe)==0,""," and A.CATN IN ('"+SUBSTITUTE(awe,",","','")+"')")}
${if(len(CATN) == 0,"","and A.CATN in ('" + CATN + "')")}
${if(len(PRDN) == 0,"","and A.PRDN in ('" + PRDN + "')")}
AND DATES=TO_CHAR(SYSDATE,'YYYY') 
GROUP BY  PROVINCE) A

LEFT JOIN 

(SELECT
	SUM(SALEQTY) AS QTY,
	ROUND(SUM(SALEPRICE)/10000,2) AS TOTAL_PRICE,
	PROVINCE
FROM
	DW_SALE_PRICE A
		LEFT JOIN TABLE_STRATEGIC C
	ON A.CATEGORYNAME=C.VARIETIES
WHERE 1=1
${if(len(STRATEGICCHANNEL) == 0,"","and C.STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}
${if(len(DEPARTMENT) == 0,"","and DEPARTMENT in ('" + DEPARTMENT + "')")}
${if(len(awe)==0,""," and CATEGORYNAME IN ('"+SUBSTITUTE(awe,",","','")+"')")}
${if(len(CATN) == 0,"","and CATEGORYNAME in ('" + CATN + "')")}
${if(len(PRDN) == 0,"","and PRDN in ('" + PRDN + "')")}
AND SUBSTR(POSTDATE,1,4)=TO_CHAR(SYSDATE,'YYYY')

GROUP BY PROVINCE)  B
 
ON A.PROVINCE=B.PROVINCE
WHERE 1=1
${if(qwe='全国',""," and A.PROVINCE IN ('"+SUBSTITUTE(qwe,",","','")+"')")}

------------------------执行进度----
SELECT
    TOTAL_PRICE,
    TARGET_PRICE,
	ROUND (TOTAL_PRICE / TARGET_PRICE, 4) RATE,
	ROUND (QTY / TARGET_QTY, 4) AS QTY_RATE
FROM
	(
		SELECT
			1 AS FLAG,
			ROUND (SUM(MONTH_PRICE), 2) AS TARGET_PRICE,
			ROUND (SUM (MONTH_PRICE * 10000 / UNITPRICE),0) AS TARGET_QTY
		FROM
			AREANAME_TARGET_PRICE A
		LEFT JOIN (SELECT DISTINCT PRDN,UNITPRICE FROM  PRODUCT) C ON A .PRDN = C.PRDN
		WHERE DATES = TO_CHAR (SYSDATE, 'YYYY')
		and DEPT!='电商事业部'
		AND FLAG='部门'
		${if(len(STRATEGICCHANNEL) == 0,"","and CHANNEL_TYPE in ('" + STRATEGICCHANNEL + "')")}
          ${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}	
          ${if(len(DEPARTMENT) == 0,"","and A.DEPT in ('" + DEPARTMENT + "')")}
          ${if(len(awe)==0,""," and A.CATN IN ('"+SUBSTITUTE(awe,",","','")+"')")}
          ${if(len(CATN) == 0,"","and A.CATN in ('" + CATN + "')")}
          ${if(len(PRDN) == 0,"","and A.PRDN in ('" + PRDN + "')")}
	) A
LEFT JOIN

 (
	SELECT
		1 AS FLAG,
		SUM (SALEQTY) AS QTY,
		ROUND (SUM(SALEPRICE) / 10000, 2) AS TOTAL_PRICE
	FROM
		DW_SALE_PRICE A
     LEFT JOIN TABLE_STRATEGIC C
	ON A.CATEGORYNAME=C.VARIETIES
	WHERE SUBSTR (POSTDATE, 1, 4) = TO_CHAR (SYSDATE, 'YYYY')
     ${if(len(STRATEGICCHANNEL) == 0,"","and C.STRATEGICCHANNEL in ('" + STRATEGICCHANNEL + "')")}
	${if(len(PROVINCE) == 0,"","and PROVINCE in ('" + PROVINCE + "')")}
     ${if(len(DEPARTMENT) == 0,"","and DEPARTMENT in ('" + DEPARTMENT + "')")}
     ${if(len(awe)==0,""," and CATEGORYNAME IN ('"+SUBSTITUTE(awe,",","','")+"')")}
     ${if(len(CATN) == 0,"","and CATEGORYNAME in ('" + CATN + "')")}
     ${if(len(PRDN) == 0,"","and PRDN in ('" + PRDN + "')")}	
) B 
ON A.FLAG=B.FLAG

SELECT * FROM REPORT_REMARK  WHERE REPORTNAME='省份天花板'

SELECT DISTINCT STRATEGICCHANNEL FROM TABLE_STRATEGIC  WHERE STRATEGICCHANNEL !='电商事业部'


