
SELECT
*  FROM V_STOCK A
LEFT JOIN PRODUCT ON A.PRODCODE=PRODUCT.PRODCODE
WHERE
	BAKCHAR04ATTR = 'FILL'
${IF(LEN(SDATE)=0,"","AND A.SDATE='"+SDATE+"'")}
${if(qwe='全国',""," and REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}
${IF(LEN(ORGCODE)=0,"","AND A.ORGCODE IN ('"+ORGCODE+"')")}
${IF(LEN(PRODCODE)=0,"","AND A.PRODCODE IN ('"+SUBSTITUTE(PRODCODE,",","','")+"')")}
${IF(LEN(PERSON)=0,"","AND A.BAKCHAR03ATTR  IN ('"+PERSON+"')")}
${IF(LEN(CUSTOMTYPE)=0,"","AND A.CUSTOMTYPE='"+CUSTOMTYPE+"'")}
${IF(LEN(GRADE)=0,"","AND A.GRADE  IN ('"+GRADE+"')")}
ORDER BY 
A.SDATE,
	A.SELLERID,
	A.PRODCODE



select distinct categorycode,catn,prodcode,prdn from product
order by catn,prodcode

SELECT  A.REGIONNAME FROM REGION A
WHERE  A.REGIONNAME NOT IN ('台湾省','香港特区','澳门特区','河北唐秦','全国')
--${if(len(PROVINCE) == 0,"","and REGIONNAME in ('" + PROVINCE + "')")}
${if(qwe='全国',""," and A.REGIONNAME IN ('"+SUBSTITUTE(qwe,",","','")+"')")}

SELECT
	DISTINCT 
	B.ORGCODE,
	B.ORGCODE||'-'||B.ORGNAME
FROM
	HISTORYOFDAYINVENTORY A
	LEFT JOIN ORGANIZATION B ON A.SELLERID = B.ORGID
	LEFT JOIN PRODUCTLANG C ON A.PRODID = C.PRODID 
	AND C.LANGUAGECODE = 'cn'
	LEFT JOIN PRODUCT D ON D.PRODID = A.PRODID
	LEFT JOIN CATEGORYLANG E ON E.CATEGORYID = A.CATEGORYID 
	AND E.LANGUAGECODE = 'cn'
	LEFT JOIN REGION F ON F.REGIONCODE=B.REGIONCODE
	LEFT JOIN CITY G ON G.CITYCODE=B.CITYCODE
	LEFT JOIN MASTERRELATIONSHIP H ON A.SELLERID=H.ORGID AND A.PRODID=H.PRODID
	LEFT JOIN BUSINESSAREA I ON H.BUSINESSAREAID=I.AREAID
	LEFT JOIN BUSINESSAREA J ON J.AREAID=I.PARENTAREAID
WHERE
	A.BAKCHAR04ATTR = 'FILL'
ORDER BY ORGCODE 

SELECT
	A.BAKCHAR03ATTR
FROM
	HISTORYOFDAYINVENTORY A

