
SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)


SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd') AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')



SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_COST),
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd')
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
AREA_CODE != '00'
--GROUP BY AREA_CODE

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '否'
AND 
DTP = '否'
AND
ATTribute = '加盟'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-DD') 
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-DD')
--GROUP BY AREA_CODE


SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)



SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
--GROUP BY AREA_CODE
--,AREA_NAME
AND
AREA_CODE != '00'


SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
--GROUP BY AREA_CODE
AND 
AREA_CODE != '00'

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,
--AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
ATTribute = '直营'
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-DD') 
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-DD')
--GROUP BY AREA_CODE

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '否'
AND 
DTP = '否'
AND
ATTribute = '加盟'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1)
--GROUP BY AREA_CODE

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '否'
AND 
DTP = '否'
AND
ATTribute = '加盟'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12)
--GROUP BY AREA_CODE

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd') 
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
ATTRIBUTE = '批发'
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'

--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
ATTRIBUTE = '批发'
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
ATTRIBUTE = '批发'
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
DTP = '是' 
AND 
AREA_CODE != '00'
--AND
--RELATED_PARTY_TRNSACTION = '否'
AND 
SALE_DATE >= TO_DATE('${DATE1}','YYYY-MM-dd') 
AND  
SALE_DATE <= TO_DATE('${DATE2}','YYYY-MM-dd')
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
DTP = '是' 
AND 
AREA_CODE != '00'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1)
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
DTP = '是' 
AND 
AREA_CODE != '00'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12)
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '是' 
AND 
AREA_CODE != '00'
AND 
SALE_DATE >= TO_DATE('${DATE1}','YYYY-MM-dd') 
AND  
SALE_DATE <= TO_DATE('${DATE2}','YYYY-MM-dd')


SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '是' 
AND 
AREA_CODE != '00'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1)
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
OTO = '是' 
AND 
AREA_CODE != '00'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12)
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
ATTribute = '直营'
AND
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12)
--GROUP BY AREA_CODE

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
--,AREA_CODE AS 子公司编码
--,AREA_NAME AS 子公司名称
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
ATTRIBUTE = '直营'
AND
DTP = '否'
AND 
OTO = '否'
AND 
AREA_CODE != '00'
and  
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1)
---GROUP BY AREA_CODE

SELECT DISTINCT
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END AS COMPARE,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY
WHERE
--AREA_CODE = AREA_CODE
--and
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(TO_DATE('${date1}','YYYY-MM-DD'),'YYYY-MM-DD')
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(TO_DATE('${date2}','YYYY-MM-DD'),'YYYY-MM-DD')
GROUP BY 
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END
--,AREA_CODE

SELECT DISTINCT
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END AS COMPARE,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY 
WHERE  
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'

AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}

AND

TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12),'YYYY-MM-DD')
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12),'YYYY-MM-DD')
GROUP BY 
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END
--,a.AREA_CODE

SELECT DISTINCT
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END AS COMPARE,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY 
WHERE  
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1),'YYYY-MM-DD')
and
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1),'YYYY-MM-DD')
GROUP BY 
CASE WHEN
TIME = '新店'
THEN
'新店'
WHEN
TIME = '次新店'
THEN
'次新店'
ELSE
'可比店'
END
--,a.AREA_CODE

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'
AND 
RELATED_PARTY_TRNSACTION = '否'
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}

AND 
ATTRIBUTE = '批发'
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND
OTO = '否'
AND 
DTP = '否'
AND 
AREA_CODE != '00'
AND 
RELATED_PARTY_TRNSACTION = '否'
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}

AND 
ATTRIBUTE = '批发'
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
--AREA_CODE AS 子公司编码,
--AREA_NAME AS 子公司名称,
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd') 
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND 
DTP = '否'
AND 
OTO = '否'
AND 
AREA_CODE != '00'
AND 
RELATED_PARTY_TRNSACTION = '否'
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}

AND 
ATTRIBUTE = '批发'
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT A.AREA_CODE,A.AREA_NAME from  DIM_REGION A left join user_limit B on A.area_code=B.area_code where 
${if(fr_username='admin',"1=1","B.username in '"+fr_username+"'")}

SELECT 
DISTINCT
TIME AS 年限,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY 
WHERE  
TIME in ('第三年店','第四年店','第五年以上店')
and
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(TO_DATE('${date1}','YYYY-MM-DD'),'YYYY-MM-DD')
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(TO_DATE('${date2}','YYYY-MM-DD'),'YYYY-MM-DD')
GROUP BY 
TIME
--,A.AREA_CODE

SELECT DISTINCT
TIME AS 年限,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY 
WHERE  
TIME in ('第三年店','第四年店','第五年以上店')
and
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12),'YYYY-MM-DD')
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12),'YYYY-MM-DD')
GROUP BY 
TIME
--,a.AREA_CODE

SELECT DISTINCT
TIME AS 年限,
SUM(NO_TAX_AMOUNT) AS 无税销售额,
SUM(NO_TAX_COST) AS 无税成本，
SUM(NO_TAX_AMOUNT)-SUM(NO_TAX_COST) AS 无税毛利额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 无税毛利率
FROM
DM_SHOP_COMPANY
WHERE  
TIME in ('第三年店','第四年店','第五年以上店')
AND
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
and
DTP = '否'
AND
OTO = '否'
AND 
AREA_CODE != '00'
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') >= TO_CHAR(ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1),'YYYY-MM-DD')
AND
TO_CHAR(SALE_DATE,'YYYY-MM-DD') <= TO_CHAR(ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1),'YYYY-MM-DD')
GROUP BY 
TIME
--,a.AREA_CODE


SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST)) AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd')
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND AREA_CODE= '00'
GROUP BY AREA_CODE



SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND AREA_CODE= '00'
GROUP BY AREA_CODE,AREA_NAME

SELECT 
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))  AS 无税毛利额,
SUM(NO_TAX_AMOUNT) as 无税销售额,
CASE WHEN 
SUM(NO_TAX_AMOUNT) = 0
then 0 
ELSE
(SUM(NO_TAX_AMOUNT) - SUM(NO_TAX_COST))/
SUM(NO_TAX_AMOUNT) 
END
as 毛利率
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND AREA_CODE= '00'
GROUP BY AREA_CODE


SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
AREA_CODE != '00'
AND
DTP = '是' 
AND
RELATED_PARTY_TRNSACTION = '否'
AND 
SALE_DATE >= TO_DATE('${DATE1}','YYYY-MM-dd') 
AND  
SALE_DATE <= TO_DATE('${DATE2}','YYYY-MM-dd')

SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
DTP = '是' 
AND 
AREA_CODE != '00'
AND 
RELATED_PARTY_TRNSACTION = '否'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-1) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-1)
--GROUP BY AREA_CODE
--,AREA_NAME

SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM
DM_MONTHLY_COMPANY
WHERE
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND
DTP = '是' 
AND 
AREA_CODE != '00'
AND 
RELATED_PARTY_TRNSACTION = '否'
AND 
SALE_DATE >= ADD_MONTHS(TO_DATE('${date1}','YYYY-MM-DD'),-12) 
AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${date2}','YYYY-MM-DD'),-12)
--GROUP BY AREA_CODE
--,AREA_NAME


SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd')
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
AREA_CODE != '00'
AND
RELATED_PARTY_TRNSACTION = '否'


SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
AREA_CODE != '00'
AND
RELATED_PARTY_TRNSACTION = '否'


SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND 
1=1
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}
AND 
AREA_CODE != '00'
AND
RELATED_PARTY_TRNSACTION = '否'

SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE 
SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd')
AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND AREA_CODE= '00'
AND
RELATED_PARTY_TRNSACTION = '否'
GROUP BY AREA_CODE



SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND AREA_CODE= '00'
AND
RELATED_PARTY_TRNSACTION = '否'
GROUP BY AREA_CODE

SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND AREA_CODE= '00'
AND
RELATED_PARTY_TRNSACTION = '否'
GROUP BY AREA_CODE


SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= TO_DATE('${date1}','YYYY-MM-dd') AND  
SALE_DATE <= TO_DATE('${date2}','YYYY-MM-dd')
AND
RELATED_PARTY_TRNSACTION = '否'




SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-12) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-12)
AND
RELATED_PARTY_TRNSACTION = '否'



SELECT 
SUM(NO_TAX_AMOUNT) as 无税销售额
FROM DM_MONTHLY_COMPANY
WHERE SALE_DATE >= ADD_MONTHS(TO_DATE('${DATE1}','YYYY-MM-dd'),-1) AND  
SALE_DATE <= ADD_MONTHS(TO_DATE('${DATE2}','YYYY-MM-dd'),-1)
AND
RELATED_PARTY_TRNSACTION = '否'



SELECT DISTINCT AREA_NAME from  DIM_REGION
WHERE 
1=1 
${if(len(SUBSIDIARY_COMPANY)=0,""," and AREA_CODE in ('"+SUBSIDIARY_COMPANY+"')")}

