SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT1,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.05',
                                                'JL',
                                                '${ISNAACCOUNT}')+
                                                SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                '${CURRENCYID}',
                                                '2221.01.01.05',
                                                'JC',
                                                '${ISNAACCOUNT}')) AMOUNT2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.07',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.08',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT4,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.09',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT5,
       (CASE
         WHEN SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.01.02',
                                                       'JC',
                                                       '${ISNAACCOUNT}') > 0 THEN
          SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                   SUBSTR('${YEARMONTH}',
                                                          0,
                                                          4) || '-01',
                                                   '${CURRENCYID}',
                                                   '2221.01.02',
                                                   'JC',
                                                   '${ISNAACCOUNT}') * (-1)
         ELSE
          SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                   SUBSTR('${YEARMONTH}',
                                                          0,
                                                          4) || '-01',
                                                   '${CURRENCYID}',
                                                   '2221.01.02',
                                                   'DC',
                                                   '${ISNAACCOUNT}')
       END) AMOUNT6,
       (CASE
         WHEN SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       '${YEARMONTH}',
                                                       '${CURRENCYID}',
                                                       '2221.01.05.01',
                                                       'JY',
                                                       '${ISNAACCOUNT}') > 0 THEN
          SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                   '${YEARMONTH}',
                                                   '${CURRENCYID}',
                                                   '2221.01.05.01',
                                                   'JY',
                                                   '${ISNAACCOUNT}') * (-1)
         ELSE
          SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                   '${YEARMONTH}',
                                                   '${CURRENCYID}',
                                                   '2221.01.05.01',
                                                   'DY',
                                                   '${ISNAACCOUNT}') * (-1)
       END) AMOUNT7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.03',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.01.06',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT9,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.01.08.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT10
  FROM DUAL


SELECT DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.02.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.02.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.02.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT1,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.03.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.03.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.03.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT2,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.04.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.04.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.04.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT3,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.05.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.05.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.05.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT4,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.06.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.06.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.06.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT5,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.07.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.07.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.07.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT6,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.08.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.08.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR(SUBSTR('${YEARMONTH}',
                                                                     0,
                                                                     4) ||
                                                              '-01',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.08.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT7,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.09.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.09.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.09.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT8,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT9,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT10,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.02',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.02',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.10.01.02',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT11,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.11.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.11.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.11.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT12,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.12.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.12.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.12.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT13,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.13.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.13.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.13.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT14,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.14.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.14.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.14.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT15,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.15.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.15.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.15.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT16,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.16.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.16.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.16.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT17,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.18.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.18.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.18.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT18,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.19.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.19.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.19.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT19,
       DECODE(SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.17.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}'),
              0,
              -1 *
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.17.01',
                                                       'JC',
                                                       '${ISNAACCOUNT}'),
              SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                       SUBSTR('${YEARMONTH}',
                                                              0,
                                                              4) || '-01',
                                                       '${CURRENCYID}',
                                                       '2221.17.01',
                                                       'DC',
                                                       '${ISNAACCOUNT}')) AMOUNT20,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '2221.99.01',
                                                 'DC',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 SUBSTR('${YEARMONTH}', 0, 4) ||
                                                 '-01',
                                                 '${CURRENCYID}',
                                                 '2221.21.01',
                                                 'DC',
                                                 '${ISNAACCOUNT}')) AMOUNT21
  FROM DUAL


SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.02.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT1,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.03.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.04.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.05.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT4,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.06.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT5,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.07.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT6,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.08.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.09.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT9,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT10,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.02',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT11,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.11.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT12,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.12.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT13,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.13.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT14,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.14.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT15,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.15.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT16,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.16.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT17,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.18.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT18,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.19.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT19,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.17.01',
                                                'DL',
                                                '${ISNAACCOUNT}') AMOUNT20,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '2221.99.01',
                                                 'DL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '2221.21.01',
                                                 'DL',
                                                 '${ISNAACCOUNT}')) AMOUNT21
  FROM DUAL


SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.02.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT1,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.03.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.04.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.05.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT4,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.06.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT5,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.07.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT6,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.08.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.09.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT9,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT10,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.02',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT11,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.11.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT12,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.12.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT13,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.13.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT14,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.14.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT15,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.15.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT16,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.16.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT17,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.18.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT18,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.19.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT19,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.17.01',
                                                'JL',
                                                '${ISNAACCOUNT}') AMOUNT20,
       (SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '2221.99.01',
                                                 'JL',
                                                 '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                 '${YEARMONTH}',
                                                 '${CURRENCYID}',
                                                 '2221.21.01',
                                                 'JL',
                                                 '${ISNAACCOUNT}')) AMOUNT21
  FROM DUAL


SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.02.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT1,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.03.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT2,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.04.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT3,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.05.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT4,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.06.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT5,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.07.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT6,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.08.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT7,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.09.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT8,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT9,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT10,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.02',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT11,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.11.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT12,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.12.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT13,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.13.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT14,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.14.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT15,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.15.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT16,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.16.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT17,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.18.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT18,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.19.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT19,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.17.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT20,
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.99.01',
                                                'DY',
                                                '${ISNAACCOUNT}') AMOUNT21
  FROM DUAL


select name bzdw from sa_oporg where id='${organId}'

SELECT SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.02.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.03.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.04.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.05.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.06.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.07.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.08.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.09.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.10.01.02',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.11.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.12.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.13.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.14.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.15.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.16.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.17.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.18.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.19.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.20.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.21.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') +
       SOLAR_FN_LEDGER.F_GET_ACCOUNT_BALANCE_NA('${ORGANID}',
                                                '${YEARMONTH}',
                                                '${CURRENCYID}',
                                                '2221.99.01.01',
                                                'JY',
                                                '${ISNAACCOUNT}') AMOUNT
  FROM DUAL


