SELECT ORGUNIT.ID,ORGUNIT.OBJNAME 
,(SELECT COUNT(1) FROM WEAVER.DBO.HUMRES WHERE ORGID=ORGUNIT.ID 
AND HRSTATUS='4028804c16acfbc00116ccba13802935') AS PersonCount
FROM [dbo]A.[DepRatio]A
LEFT JOIN WEAVER.DBO.ORGUNIT ON [DepRatio]A.ID=ORGUNIT.ID
ORDER BY ORGUNIT.DSPORDER

SELECT [WorkInfo]A.PerID,HUMRES.OBJNO,HUMRES.OBJNAME,ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName 
,[WorkInfo]A.OfficeAddress,[PersonTemperature]A.[Temperature]A
FROM [dbo]A.[WorkInfo]A
LEFT JOIN WEAVER.DBO.HUMRES ON [WorkInfo]A.PERID=HUMRES.ID
LEFT JOIN WEAVER.DBO.ORGUNIT ON HUMRES.ORGID=ORGUNIT.ID
LEFT JOIN [dbo]A.[PersonTemperature]A ON [WorkInfo]A.PerID=[PersonTemperature]A.PerID 
AND [WorkInfo]A.SubmitDate=[PersonTemperature]A.SubmitDate
WHERE [WorkInfo]A.SubmitDate='${SubmitDate}'
ORDER BY ORGUNIT.DSPORDER

SELECT HUMRES.ID,HUMRES.OBJNO,HUMRES.OBJNAME,ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName 
FROM 
(
SELECT RIGHT(pin,4) AS WorkNo FROM
[CHECKIN]A.[zkteco_database]A.[dbo]A.[checkinout]A
WHERE CONVERT(varchar(100),Checktime, 23)='${SubmitDate}'
GROUP BY RIGHT(pin,4)
) AS ck
LEFT JOIN HUMRES ON ck.WorkNo=HUMRES.OBJNO
LEFT JOIN ORGUNIT ON HUMRES.ORGID=ORGUNIT.ID
UNION
SELECT HUMRES.ID,HUMRES.OBJNO,HUMRES.OBJNAME,ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName FROM  
(
SELECT uf_doorcontrol.employeeld AS WorkNo FROM uf_doorcontrol
WHERE CONVERT(varchar(100),CAST(EVENTDATE AS DATETIME), 23)='${SubmitDate}'
GROUP BY uf_doorcontrol.employeeld
) AS dc
LEFT JOIN HUMRES ON dc.WorkNo = HUMRES.OBJNO
LEFT JOIN ORGUNIT ON HUMRES.ORGID=ORGUNIT.ID
WHERE HUMRES.ID IS NOT NULL

SELECT HUMRES.ID,HUMRES.OBJNO,HUMRES.OBJNAME,ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName,[PersonTemperature]A.[Temperature]A
FROM 
(
SELECT RIGHT(pin,4) AS WorkNo FROM
[CHECKIN]A.[zkteco_database]A.[dbo]A.[checkinout]A
WHERE CONVERT(varchar(100),Checktime, 23)='${SubmitDate}'
GROUP BY RIGHT(pin,4)
) AS ck
LEFT JOIN HUMRES ON ck.WorkNo=HUMRES.OBJNO
LEFT JOIN ORGUNIT ON HUMRES.ORGID=ORGUNIT.ID
LEFT JOIN FineBI.dbo.[PersonTemperature]A ON HUMRES.ID=[PersonTemperature]A.PerID AND SubmitDate='${SubmitDate}'
WHERE HUMRES.ID NOT IN (SELECT PerID FROM FineBI.dbo.WorkInfo WHERE SubmitDate='${SubmitDate}')
UNION
SELECT HUMRES.ID,HUMRES.OBJNO,HUMRES.OBJNAME,ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName,[PersonTemperature]A.[Temperature]A 
FROM  
(
SELECT uf_doorcontrol.employeeld AS WorkNo FROM uf_doorcontrol
WHERE CONVERT(varchar(100),CAST(EVENTDATE AS DATETIME), 23)='${SubmitDate}'
GROUP BY uf_doorcontrol.employeeld
) AS dc
LEFT JOIN HUMRES ON dc.WorkNo = HUMRES.OBJNO
LEFT JOIN ORGUNIT ON HUMRES.ORGID=ORGUNIT.ID
LEFT JOIN FineBI.dbo.[PersonTemperature]A ON HUMRES.ID=[PersonTemperature]A.PerID AND SubmitDate='${SubmitDate}'
WHERE HUMRES.ID IS NOT NULL AND HUMRES.ID NOT IN (SELECT PerID FROM FineBI.dbo.WorkInfo WHERE SubmitDate='${SubmitDate}')

SELECT ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName,PerCount FROM
(
SELECT DepID,COUNT(PerID) AS PerCount FROM
(
SELECT CASE DepRatio.DepType WHEN 1 THEN '8a81f38e3e264c99013e3026afd60016'
WHEN 2 THEN '8a8182fe5494ed670154e0ab8bf13315' 
WHEN 3 THEN '8a81f3e93f416ef8013f4170abc30002'
WHEN 4 THEN '8a81f38e3e264c99013e3026557a0014'
ELSE HUMRES.ORGID END AS DepID
,WorkInfo.PerID
FROM [dbo]A.[WorkInfo]A
LEFT JOIN WEAVER.DBO.HUMRES ON [WorkInfo]A.PERID=HUMRES.ID
LEFT JOIN DepRatio ON HUMRES.ORGID=DepRatio.ID
WHERE [WorkInfo]A.SubmitDate='${SubmitDate}'
) AS Tab
GROUP BY DepID
) AS tmp 
LEFT JOIN WEAVER.DBO.ORGUNIT ON tmp.DepID=ORGUNIT.ID
ORDER BY ORGUNIT.DSPORDER

SELECT ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName,PerCount FROM
(
SELECT DepID,COUNT(PerID) AS PerCount FROM
(
SELECT CASE DepType WHEN 1 THEN '8a81f38e3e264c99013e3026afd60016'
WHEN 2 THEN '8a8182fe5494ed670154e0ab8bf13315' 
WHEN 3 THEN '8a81f3e93f416ef8013f4170abc30002'
WHEN 4 THEN '8a81f38e3e264c99013e3026557a0014'
ELSE DepID END AS DepID
,PerID
FROM
(
SELECT HUMRES.ID AS PerID,HUMRES.ORGID AS DepID,DepType
FROM 
(
SELECT RIGHT(pin,4) AS WorkNo FROM
[CHECKIN]A.[zkteco_database]A.[dbo]A.[checkinout]A
WHERE CONVERT(varchar(100),Checktime, 23)='${SubmitDate}'
GROUP BY RIGHT(pin,4)
) AS ck
LEFT JOIN HUMRES ON ck.WorkNo=HUMRES.OBJNO
LEFT JOIN FineBI.dbo.DepRatio ON HUMRES.ORGID=DepRatio.ID
UNION
SELECT HUMRES.ID AS PerID,HUMRES.ORGID AS DepID,DepType
FROM  
(
SELECT uf_doorcontrol.employeeld AS WorkNo FROM uf_doorcontrol
WHERE CONVERT(varchar(100),CAST(EVENTDATE AS DATETIME), 23)='${SubmitDate}'
GROUP BY uf_doorcontrol.employeeld
) AS dc
LEFT JOIN HUMRES ON dc.WorkNo = HUMRES.OBJNO
LEFT JOIN FineBI.dbo.DepRatio ON HUMRES.ORGID=DepRatio.ID
WHERE HUMRES.ID IS NOT NULL
) AS tmp
) AS tmp1
GROUP BY DepID
) AS tmp2
LEFT JOIN ORGUNIT ON tmp2.DepID=ORGUNIT.ID
ORDER BY ORGUNIT.DSPORDER

SELECT ORGUNIT.ID AS DepID,ORGUNIT.OBJNAME AS DepName,PerCount FROM
(
SELECT DepID,COUNT(PerID) AS PerCount FROM
(
SELECT CASE DepType WHEN 1 THEN '8a81f38e3e264c99013e3026afd60016'
WHEN 2 THEN '8a8182fe5494ed670154e0ab8bf13315' 
WHEN 3 THEN '8a81f3e93f416ef8013f4170abc30002'
WHEN 4 THEN '8a81f38e3e264c99013e3026557a0014'
ELSE DepID END AS DepID,PerID
FROM
(
SELECT HUMRES.ID AS PerID,HUMRES.ORGID AS DepID,DepRatio.DepType
FROM 
(
SELECT RIGHT(pin,4) AS WorkNo FROM
[CHECKIN]A.[zkteco_database]A.[dbo]A.[checkinout]A
WHERE CONVERT(varchar(100),Checktime, 23)='${SubmitDate}'
GROUP BY RIGHT(pin,4)
) AS ck
LEFT JOIN HUMRES ON ck.WorkNo=HUMRES.OBJNO
LEFT JOIN FineBI.dbo.DepRatio ON HUMRES.ORGID=DepRatio.ID
WHERE HUMRES.ID NOT IN (SELECT PerID FROM FineBI.dbo.WorkInfo WHERE SubmitDate='${SubmitDate}')
UNION
SELECT HUMRES.ID AS PerID,HUMRES.ORGID AS DepID,DepRatio.DepType
FROM  
(
SELECT uf_doorcontrol.employeeld AS WorkNo FROM uf_doorcontrol
WHERE CONVERT(varchar(100),CAST(EVENTDATE AS DATETIME), 23)='${SubmitDate}'
GROUP BY uf_doorcontrol.employeeld
) AS dc
LEFT JOIN HUMRES ON dc.WorkNo = HUMRES.OBJNO
LEFT JOIN FineBI.dbo.DepRatio ON HUMRES.ORGID=DepRatio.ID
WHERE HUMRES.ID IS NOT NULL AND HUMRES.ID NOT IN (SELECT PerID FROM FineBI.dbo.WorkInfo WHERE SubmitDate='${SubmitDate}')
) AS Tab
) AS tmp
GROUP BY DepID
) AS tmp1
LEFT JOIN ORGUNIT ON tmp1.DepID=ORGUNIT.ID
ORDER BY ORGUNIT.DSPORDER

