SELECT 
       A.BILL_NO, --验收单号
       P1.PARTY_NAME AS RECEIVE_PARTY_NAME, --收货单位
       P1.PARTY_OPCODE AS RECEIVE_PARTY_CODE, --收货单位编码
       P2.PARTY_NAME AS SEND_PARTY_NAME, --供货单位
       P2.PARTY_OPCODE AS SEND_PARTY_CODE, --供货单位编码
       A.RECEIVE_DATE, --验收日期
       A.Receiver,
       P3.PARTY_NAME AS CHECKER1,
       P4.PARTY_NAME AS CHECKER2,
       G.GOODS_OPCODE,
       
       G.GOODS_NAME || '/' || F.GOODS_FORM || '/' ||  G.GOODS_DESC || '/' || 
       P4.PARTY_NAME  goods_name,
       B.RECEIVE_QTY,
       B.LOCATE_QTY,
       L.LOT_NO,
       L.PRODUCE_DATE,
       L.EXPIRE_DATE,
       G.AUTH_DOCNO,
       G.MID_PACKNUM || '/' || G.PACKAGE_NUM AS PACKAGE_NUM,
       C.CATAGORY,
       G.RETAIL_PRICE
FROM wx_prod.SSC_RECEIVE_GOODS A
INNER JOIN wx_prod.SSC_RECEIVE_GOODS_LINES B ON A.SSC_RECEIVE_GOODS_ID = B.SSC_RECEIVE_GOODS_ID
LEFT JOIN wx_prod.COM_PARTY P1 ON A.RECEIVE_PARTY_ID = P1.COM_PARTY_ID
LEFT JOIN wx_prod.COM_PARTY P2 ON A.SEND_PARTY_ID = P2.COM_PARTY_ID
LEFT JOIN wx_prod.COM_PARTY P3 ON A.CHECKER = P3.COM_PARTY_ID
LEFT JOIN wx_prod.COM_PARTY P4 ON A.CHECKER1 = P4.COM_PARTY_ID
INNER JOIN wx_prod.COM_GOODS G ON B.COM_GOODS_ID = G.COM_GOODS_ID
LEFT JOIN wx_prod.COM_GOODS_FORM F ON G.COM_GOODS_FORM_ID = F.COM_GOODS_FORM_ID
LEFT JOIN wx_prod.COM_FACTORY T ON G.FACTORY_ID = T.COM_PARTY_ID
LEFT JOIN wx_prod.COM_PARTY P4 ON T.COM_PARTY_ID = P4.COM_PARTY_ID
LEFT JOIN wx_prod.COM_LOT L ON B.COM_LOT_ID = L.COM_LOT_ID
LEFT JOIN wx_prod.COM_GOODS_CATAGORY C ON G.GOODS_CATAGORY_ID = C.COM_GOODS_CATAGORY_ID
WHERE 1=1
${if(len(sscReceiveGooodsId)>0,"AND A.SSC_RECEIVE_GOODS_ID ='"+sscReceiveGooodsId+"'","")}
${if(len(startDate)>0,"AND A.RECEIVE_DATE >=d('"+startDate+"')","")}
${if(len(endDate)>0,"AND A.RECEIVE_DATE <d('"+endDate+"')+1","")}
${if(len(billNo) > 0," and A.BILL_NO like '"+billNo+"%'","")}
${if(len(goodsCode)>0,"AND EXISTS (SELECT 1 FROM wx_prod.COM_GOODS G WHERE B.COM_GOODS_ID = G.COM_GOODS_ID AND G.GOODS_OPCODE LIKE '%"+goodsCode+"%')","")}
${if(len(goodsInfo)>0,"AND EXISTS (SELECT 1 FROM wx_prod.COM_GOODS G WHERE B.COM_GOODS_ID = G.COM_GOODS_ID AND G.GOODS_NAME LIKE '%"+goodsInfo+"%')","")}

