SELECT DISTINCT THE_MONTH FROM DIM_TIME 
WHERE LEFT(THE_MONTH,4) = CONVERT(VARCHAR(4),GETDATE()-1,120)
AND THE_MONTH < = CONVERT(VARCHAR(7),GETDATE()-1,120)
AND THE_MONTH >'2021-03'

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

select AREANAME FROM (
SELECT  distinct AREANAME 
FROM   DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)) A
WHERE AREANAME = '珠海大区'


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT CITYNAME FROM (
select distinct CITYNAME from DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")} ) A
ORDER BY charindex(CITYNAME,'珠海华欣|珠海华景|珠海西区|斗门|中山|广州|南宁|上海|南京|沈阳|大连|包头|')

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT DISTINCT PROJECTID,'('+PROJECTID+')'+ ISNULL(SALERGROUPNAME,PROJECTNAME) PROJECTNAME FROM DIM_MKT_PROJECT
WHERE PROJECTID IN
(
	SELECT DISTINCT DEPT_ID FROM user_org 
)  
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")}
${if(len(CITY) == 0,"","and CITYNAME in ('" + CITY + "')")}

SELECT DISTINCT PRODUCTID,PRODUCTNAME FROM DIM_PRODUCT_TYPE WHERE PRODUCT_TYPE = '02'


WITH T1 AS(
------------------- 操盘项目回款
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月前认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DYHK1 ELSE 0 END )/10000,2) MHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DHK1 ELSE 0 END )/10000,2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN isnull(DYHK1,0)+isnull(KHK1,0) ELSE 0 END )/10000,2) KHK
FROM F_MKT_PROJECT_INCOME_ZH T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月至去年年底认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DYHK2 ELSE 0 END )/10000,2) MHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DHK2 ELSE 0 END )/10000,2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN isnull(DYHK2,0)+isnull(KHK2,0) ELSE 0 END )/10000,2) KHK
FROM F_MKT_PROJECT_INCOME_ZH T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'当年认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DYHK ELSE 0 END )/10000,2) MHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DHK ELSE 0 END )/10000,2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN isnull(DYHK,0)+isnull(KHK,0) ELSE 0 END )/10000,2) KHK
FROM F_MKT_PROJECT_INCOME_ZH T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
--------------------- 非操盘项目回款
union all
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月前认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income1 ELSE 0 END ),2) MHK,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN income1 ELSE 0 END ),2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN kincome1 ELSE 0 END ),2) KHK
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月至去年年底认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income2 ELSE 0 END ),2) MHK,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN income2 ELSE 0 END ),2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN kincome2 ELSE 0 END ),2) KHK
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'当年认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income ELSE 0 END ),2) MHK,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN income ELSE 0 END ),2) YHK,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN kincome ELSE 0 END ),2) KHK
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
),
T5 AS(
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月前认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income1 ELSE 0 END ),2) MHK_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN income1 ELSE 0 END),2) THK_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN income1 ELSE 0 END ),2) YHK_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,periodid,productid
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月至去年年底认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income2 ELSE 0 END ),2) MHK_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN income2 ELSE 0 END),2) THK_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN income2 ELSE 0 END ),2) YHK_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,periodid,productid
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'当年认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN income ELSE 0 END ),2) MHK_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN income ELSE 0 END),2) THK_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN income ELSE 0 END ),2) YHK_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,periodid,productid
)

SELECT 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END BELONG_COMP, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME)AREANAME, " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME)SHORTNAME, " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME) CITYNAME, " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME)PROJECTNAME,ISNULL(T3.RATIO,T5.RATIO)RATIO,ISNULL(T3.HF_RATIO,T5.HF_RATIO)HF_RATIO," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME)PERIODNAME,ISNULL(T1.PERIODID,T5.PERIODID)PERIODID," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)SALE_TYPE, " ) }
''a,
${SWITCH(TAB,0,"SUM(MHK)",1,"SUM(MHK*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(MHK*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")} MHK, 
${SWITCH(TAB,0,"SUM(YHK)",1,"SUM(YHK*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YHK*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YHK,
${SWITCH(TAB,0,"SUM(KHK)",1,"SUM(KHK*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(KHK*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}KHK,
${SWITCH(TAB,0,"SUM(MHK_AIM)",1,"SUM(MHK_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(MHK_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}MHK_AIM, 
${SWITCH(TAB,0,"SUM(THK_AIM)",1,"SUM(THK_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(THK_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}THK_AIM,
${SWITCH(TAB,0,"SUM(YHK_AIM)",1,"SUM(YHK_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YHK_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YHK_AIM
FROM T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,RATIO,HF_RATIO,CP_FLAG FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T4 ON T1.PRODUCTID=T4.PRODUCTID
FULL JOIN T5 ON T1.PERIODID = T5.PERIODID AND t1.PRODUCTID = T5.PRODUCTID  AND T1.SALE_TYPE = T5.SALE_TYPE
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T6 ON T5.PRODUCTID=T6.PRODUCTID


WHERE 1=1
-- ${if(len(AREA)=0,"","and T1.AREANAME in ('"+AREA+"')")}
${if(len(CITY)=0,"","and ISNULL(T1.CITYNAME,T5.CITYNAME) in ('"+CITY+"')")}
${if(len(PRO) == 0,"","and ISNULL(T1.PROJECTID,T5.PROJECTID) in ('" + PRO+ "')")}
${if(len(DUCT) == 0,"","and ISNULL(left(T4.PRODUCTID,4),left(T6.PRODUCTID,4))  in ('" + DUCT + "')")}
${if(len(SALE_TYPE) == 0,"","and T1.SALE_TYPE  in ('" + SALE_TYPE+ "')")}
${if(len(BELONG_COMP) == 0,"","and CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END in ('" + BELONG_COMP+ "')")}
AND ISNULL(T1.AREANAME,T5.AREANAME) = '珠海大区'

GROUP BY
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME), " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME), " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE), " ) }
ISNULL(T1.AREANAME,T5.AREANAME)


ORDER BY 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END,'股份项目|城运托管'), " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(ISNULL(T1.CITYNAME,T5.CITYNAME),'珠海华欣|珠海华景|珠海西区'),
" ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,"","  ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)," ) }
a

select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01')) else 1 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01'))*100,2) else 100 end

select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofyear(curdate())/ 365 
else datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofyear(curdate())/ 365*100,2) 
else round(datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365*100,2) end




SELECT MAX (INSERTIME) INSERTIME FROM F_MKT_PROJECT_SIGN_MORE


