SELECT DISTINCT THE_MONTH FROM DIM_TIME 
WHERE LEFT(THE_MONTH,4) = CONVERT(VARCHAR(4),GETDATE()-1,120)
AND THE_MONTH < = CONVERT(VARCHAR(7),GETDATE()-1,120)
AND THE_MONTH >'2021-02'

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

select AREANAME FROM (
SELECT  distinct AREANAME 
FROM   DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)) A
WHERE AREANAME = '珠海大区'


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT CITYNAME FROM (
select distinct CITYNAME from DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")} ) A
ORDER BY charindex(CITYNAME,'珠海华欣|珠海华景|珠海西区|斗门|中山|广州|南宁|上海|南京|沈阳|大连|包头|')

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT DISTINCT PROJECTID,'('+PROJECTID+')'+ ISNULL(SALERGROUPNAME,PROJECTNAME) PROJECTNAME FROM DIM_MKT_PROJECT
WHERE PROJECTID IN
(
	SELECT DISTINCT DEPT_ID FROM user_org 
)  
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")}
${if(len(CITY) == 0,"","and CITYNAME in ('" + CITY + "')")}

SELECT DISTINCT PRODUCTID,PRODUCTNAME FROM DIM_PRODUCT_TYPE WHERE PRODUCT_TYPE = '02'


WITH T1 AS(
------------------------操盘项目可签约，扣减版
SELECT 
T1.AREANAME,T1.CITYNAME,T1.PROJECTID,T1.PROJECTNAME,T1.PERIODNAME,T1.sale_type,T1.PERIODID,T1.PRODUCTID,KQ_AMOUNT,QY_AMOUNT,YQY_AMOUNT
FROM
(
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月前认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WDAMOUNT1 ELSE 0 END )/10000,2) QY_AMOUNT
FROM F_MKT_SALE_MONTHKPI T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
WHERE LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) 
AND LEFT(T1.PROJECTID,2)<>'HZ'
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月至去年年底认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WDAMOUNT2 ELSE 0 END )/10000,2) QY_AMOUNT
FROM F_MKT_SALE_MONTHKPI T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
WHERE LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) 
AND LEFT(T1.PROJECTID,2)<>'HZ'
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'当年认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DDAMOUNT ELSE 0 END )/10000,2) QY_AMOUNT
FROM F_MKT_SALE_MONTHKPI T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
WHERE LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) 
AND LEFT(T1.PROJECTID,2)<>'HZ'
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
)T1 LEFT JOIN
(
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月前认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WWQ_SIGN_AMOUNT1 ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN WQ_SIGN_AMOUNT1 ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月至去年年底认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WWQ_SIGN_AMOUNT2 ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN WQ_SIGN_AMOUNT2 ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'当年认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DWQ_SIGN_AMOUNT ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN DQ_SIGN_AMOUNT ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
)T2 ON T1.PERIODID = T2.PERIODID AND T1.PRODUCTID = T2.PRODUCTID AND T1.SALE_TYPE = T2.SALE_TYPE

--------------------- 非操盘项目可签约
union all
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月前认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount1 ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月至去年年底认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount2 ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'当年认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
),
T5 AS(
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月前认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount1 ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4)  AND LEN(YEARMONTH) = 4 THEN signamount1 ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID,PRODUCTID
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月至去年年底认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount2 ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN signamount2 ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'当年认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN signamount ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID
)

SELECT 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END BELONG_COMP, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME)AREANAME, " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME)SHORTNAME, " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME) CITYNAME, " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME)PROJECTNAME,ISNULL(T3.RATIO,T5.RATIO)RATIO,ISNULL(T3.HF_RATIO,T5.HF_RATIO)HF_RATIO," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME)PERIODNAME,ISNULL(T1.PERIODID,T5.PERIODID)PERIODID," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)SALE_TYPE, " ) }
''a,
${SWITCH(TAB,0,"SUM(QY_AMOUNT)",1,"SUM(QY_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(QY_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")} QY_AMOUNT, 
${SWITCH(TAB,0,"SUM(YQY_AMOUNT)",1,"SUM(YQY_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YQY_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YQY_AMOUNT,
${SWITCH(TAB,0,"SUM(KQ_AMOUNT)",1,"SUM(KQ_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(KQ_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}KQ_AMOUNT,
${SWITCH(TAB,0,"SUM(QY_AIM)",1,"SUM(QY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(QY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}QY_AIM, 
${SWITCH(TAB,0,"SUM(TQY_AIM)",1,"SUM(TQY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(TQY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}TQY_AIM,
${SWITCH(TAB,0,"SUM(YQY_AIM)",1,"SUM(YQY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YQY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YQY_AIM
FROM T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,RATIO,HF_RATIO,CP_FLAG FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T4 ON T1.PRODUCTID=T4.PRODUCTID
FULL JOIN T5 ON T1.PERIODID = T5.PERIODID AND t1.PRODUCTID = T5.PRODUCTID  AND T1.SALE_TYPE = T5.SALE_TYPE
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T6 ON T5.PRODUCTID=T6.PRODUCTID


WHERE 1=1
-- ${if(len(AREA)=0,"","and T1.AREANAME in ('"+AREA+"')")}
${if(len(CITY)=0,"","and ISNULL(T1.CITYNAME,T5.CITYNAME) in ('"+CITY+"')")}
${if(len(PRO) == 0,"","and ISNULL(T1.PROJECTID,T5.PROJECTID) in ('" + PRO+ "')")}
${if(len(DUCT) == 0,"","and ISNULL(left(T4.PRODUCTID,4),left(T6.PRODUCTID,4))  in ('" + DUCT + "')")}
${if(len(SALE_TYPE) == 0,"","and T1.SALE_TYPE  in ('" + SALE_TYPE+ "')")}
${if(len(BELONG_COMP) == 0,"","and CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END in ('" + BELONG_COMP+ "')")}
AND ISNULL(T1.AREANAME,T5.AREANAME) = '珠海大区'

GROUP BY
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME), " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME), " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE), " ) }
ISNULL(T1.AREANAME,T5.AREANAME)

ORDER BY 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END,'股份项目|城运托管'), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,"","CHARINDEX(ISNULL(T4.SHORTNAME,T6.SHORTNAME),'住宅|别墅|商业|车位')," ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(ISNULL(T1.CITYNAME,T5.CITYNAME),'珠海华欣|珠海华景|珠海西区'),
" ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,"","  ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)," ) }
a

select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01')) else 1 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01'))*100,2) else 100 end

select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofyear(curdate())/ 365 
else datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofyear(curdate())/ 365*100,2) 
else round(datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365*100,2) end




SELECT MAX (INSERTIME) INSERTIME FROM F_MKT_PROJECT_SIGN_MORE


WITH T1 AS(
------------------------操盘项目可签约，扣减版
SELECT 
AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月前认购' sale_type,T3.PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WWQ_SIGN_AMOUNT1 ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WQ_SIGN_AMOUNT1 ELSE 0 END )/10000,2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN WQ_SIGN_AMOUNT1 ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'19年7月至去年年底认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WWQ_SIGN_AMOUNT2 ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN WQ_SIGN_AMOUNT2 ELSE 0 END )/10000,2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN WQ_SIGN_AMOUNT2 ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,
'当年认购' sale_type,T3.PERIODID,left(PRODUCTID,4)PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DWQ_SIGN_AMOUNT ELSE 0 END )/10000,2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN DQ_SIGN_AMOUNT ELSE 0 END )/10000,2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN DQ_SIGN_AMOUNT ELSE 0 END )/10000,2) YQY_AMOUNT
FROM F_MKT_PROJECT_SIGN_MORE T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,PROJECTID,PROJECTNAME FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID AND T1.PROJECTID = T3.PROJECTID
GROUP BY AREANAME,CITYNAME,T3.PROJECTID,T3.PROJECTNAME,T3.PERIODNAME,T3.PERIODID,left(PRODUCTID,4)

--------------------- 非操盘项目可签约
union all
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月前认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount1 ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'19年7月至去年年底认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount2 ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'当年认购' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ksignamount ELSE 0 END ),2) KQ_AMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount ELSE 0 END ),2) QY_AMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND YEARMONTH <='${YEARMONTH}' THEN signamount ELSE 0 END ),2) YQY_AMOUNT
FROM ipt_mkt_area_kpi_target_hz
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
),
T5 AS(
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月前认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount1 ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount1 ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4)  AND LEN(YEARMONTH) = 4 THEN signamount1 ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID,PRODUCTID
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'19年7月至去年年底认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount2 ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount2 ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN signamount2 ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,periodid,productid,'当年认购' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN signamount ELSE 0 END ),2) QY_AIM,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN signamount ELSE 0 END),2) TQY_AIM,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) AND LEN(YEARMONTH) = 4 THEN signamount ELSE 0 END ),2) YQY_AIM
FROM ipt_mkt_area_kpi_target
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID
)

SELECT 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END BELONG_COMP, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME)AREANAME, " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME)SHORTNAME, " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME) CITYNAME, " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME)PROJECTNAME,ISNULL(T3.RATIO,T5.RATIO)RATIO,ISNULL(T3.HF_RATIO,T5.HF_RATIO)HF_RATIO," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME)PERIODNAME,ISNULL(T1.PERIODID,T5.PERIODID)PERIODID," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)SALE_TYPE, " ) }
''a,
${SWITCH(TAB,0,"SUM(QY_AMOUNT)",1,"SUM(QY_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(QY_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")} QY_AMOUNT, 
${SWITCH(TAB,0,"SUM(YQY_AMOUNT)",1,"SUM(YQY_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YQY_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YQY_AMOUNT,
${SWITCH(TAB,0,"SUM(KQ_AMOUNT)",1,"SUM(KQ_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(KQ_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}KQ_AMOUNT,
${SWITCH(TAB,0,"SUM(QY_AIM)",1,"SUM(QY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(QY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}QY_AIM, 
${SWITCH(TAB,0,"SUM(TQY_AIM)",1,"SUM(TQY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(TQY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}TQY_AIM,
${SWITCH(TAB,0,"SUM(YQY_AIM)",1,"SUM(YQY_AIM*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YQY_AIM*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YQY_AIM
FROM T1
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,RATIO,HF_RATIO,CP_FLAG FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T4 ON T1.PRODUCTID=T4.PRODUCTID
FULL JOIN T5 ON T1.PERIODID = T5.PERIODID AND t1.PRODUCTID = T5.PRODUCTID  AND T1.SALE_TYPE = T5.SALE_TYPE
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T6 ON T5.PRODUCTID=T6.PRODUCTID


WHERE 1=1
-- ${if(len(AREA)=0,"","and T1.AREANAME in ('"+AREA+"')")}
${if(len(CITY)=0,"","and ISNULL(T1.CITYNAME,T5.CITYNAME) in ('"+CITY+"')")}
${if(len(PRO) == 0,"","and ISNULL(T1.PROJECTID,T5.PROJECTID) in ('" + PRO+ "')")}
${if(len(DUCT) == 0,"","and ISNULL(left(T4.PRODUCTID,4),left(T6.PRODUCTID,4))  in ('" + DUCT + "')")}
${if(len(SALE_TYPE) == 0,"","and T1.SALE_TYPE  in ('" + SALE_TYPE+ "')")}
${if(len(BELONG_COMP) == 0,"","and CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END in ('" + BELONG_COMP+ "')")}
AND ISNULL(T1.AREANAME,T5.AREANAME) = '珠海大区'

GROUP BY
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME), " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME), " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE), " ) }
ISNULL(T1.AREANAME,T5.AREANAME)

ORDER BY 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END,'股份项目|城运托管'), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,"","CHARINDEX(ISNULL(T4.SHORTNAME,T6.SHORTNAME),'住宅|别墅|商业|车位')," ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(ISNULL(T1.CITYNAME,T5.CITYNAME),'珠海华欣|珠海华景|珠海西区'),
" ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,"","  ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)," ) }
a

