WITH T1 AS(
------------------  操盘项目数据，业态名称为二级
SELECT 
AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'存货' sale_type,PERIODID,left(PRODUCTID,4) PRODUCTID,ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN KST_INSIDE_AMOUNT ELSE 0 END )/10000,2) KS_AMOUNT
FROM F_MKT_PROJECT_STOCK_ALL
WHERE YEARMONTH >= '2021-03'
and areaname = '珠海大区'
and YEARMONTH = '${YEARMONTH}'
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,
'新取证' sale_type,PERIODID,left(PRODUCTID,4)PRODUCTID,ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN XTP_INSIDE_AMOUNT ELSE 0 END )/10000,2) KS_AMOUNT
FROM F_MKT_PROJECT_STOCK_ALL
WHERE YEARMONTH >= '2021-03'
and areaname = '珠海大区'
and YEARMONTH = '${YEARMONTH}'
GROUP BY AREANAME,CITYNAME,PROJECTID,PROJECTNAME,PERIODNAME,PERIODID,left(PRODUCTID,4)
union all
------------------  合作项目数据，业态名称为一级
SELECT 
areaname,cityname,projectid,projectname,periodname,
'存货' sale_type,periodid,productid,ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN stock_ks ELSE 0 END ),2) KS_AMOUNT
from  ipt_mkt_area_kpi_target_hz
where areaname = '珠海大区'
group by areaname,cityname,projectid,projectname,periodname,periodid,productid
union all
SELECT 
areaname,cityname,projectid,projectname,periodname,
'新取证' sale_type,periodid,productid,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN new_ks ELSE 0 END ),2) KS_AMOUNT
from  ipt_mkt_area_kpi_target_hz
where areaname = '珠海大区'
group by areaname,cityname,projectid,projectname,periodname,periodid,productid
),
T2 AS(
SELECT 
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.AREANAME ELSE A.AREANAME END AREANAME,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.CITYNAME ELSE A.CITYNAME END CITYNAME,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.PROJECTID ELSE A.PROJECTID END PROJECTID,
-- CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.PROJECTNAME ELSE A.PROJECTNAME END PROJECTNAME,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.PERIODID ELSE A.PERIODID END PERIODID,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.PRODUCTID ELSE A.PRODUCTID END PRODUCTID,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.sale_type ELSE A.sale_type END sale_type,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.MORDERAMOUNT ELSE A.MORDERAMOUNT END MORDERAMOUNT,
CASE WHEN '${YEARMONTH}' = '2021-03' THEN B.YORDERAMOUNT ELSE A.YORDERAMOUNT END YORDERAMOUNT
FROM(
-- 2021年三月以后取扣减版
SELECT 
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)PRODUCTID,'存货' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN CH_AMOUNT ELSE 0 END)/10000,2)  MORDERAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' and LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) THEN CH_AMOUNT ELSE 0 END)/10000,2) YORDERAMOUNT 
FROM F_MKT_SALE_MONTHKPI T1 
where areaname = '珠海大区'
GROUP BY
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)PRODUCTID,'新取证' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN ISNULL(JT_AMOUNT,0)+ISNULL(SK_AMOUNT,0) ELSE 0 END)/10000,2)  MORDERAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}'and LEFT(YEARMONTH,4) = LEFT('${YEARMONTH}',4) THEN ISNULL(JT_AMOUNT,0)+ISNULL(SK_AMOUNT,0) ELSE 0 END)/10000,2) YORDERAMOUNT 
FROM F_MKT_SALE_MONTHKPI T1
where areaname = '珠海大区'
GROUP BY
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)
) A LEFT JOIN(
-- 2021年三月取实际版，因为扣减版没有数据
SELECT 
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)PRODUCTID,'存货' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '2021-03' THEN CH_AMOUNT ELSE 0 END)/10000,2)  MORDERAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '2021-03' AND  LEFT(YEARMONTH,4) = '2021' THEN CH_AMOUNT ELSE 0 END)/10000,2) YORDERAMOUNT 
FROM F_MKT_PROJECT_SALE T1 
where areaname = '珠海大区'
GROUP BY
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)
UNION ALL
SELECT
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)PRODUCTID,'新取证' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '2021-03' THEN ISNULL(JT_AMOUNT,0)+ISNULL(SK_AMOUNT,0) ELSE 0 END)/10000,2)  MORDERAMOUNT,
ROUND(SUM(CASE WHEN LEFT(YEARMONTH,4) = LEFT('2021-03',4) THEN ISNULL(JT_AMOUNT,0)+ISNULL(SK_AMOUNT,0) ELSE 0 END)/10000,2) YORDERAMOUNT 
FROM F_MKT_PROJECT_SALE T1
where areaname = '珠海大区'
GROUP BY
AREANAME,CITYNAME,PROJECTID,PERIODID,left(PRODUCTID,4)
) B ON A.PERIODID=B.PERIODID AND A.PRODUCTID = B.PRODUCTID AND A.SALE_TYPE = B.SALE_TYPE
where a.projectid not in (select distinct projectid from ipt_mkt_area_kpi_target_hz)                -- 避免营销系统也有非操盘项目和新录入数据重复


------------------  合作项目数据，业态名称为一级
union all
SELECT 
areaname,cityname,projectid,periodid,productid,'存货' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN stock_order ELSE 0 END ),2) MORDERAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' THEN stock_order ELSE 0 END),2) YORDERAMOUNT 
from  ipt_mkt_area_kpi_target_hz
group by areaname,cityname,projectid,periodid,productid
union all
SELECT 
areaname,cityname,projectid,periodid,productid,'新取证' sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN new_order ELSE 0 END ),2) MORDERAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' THEN new_order ELSE 0 END),2) YORDERAMOUNT 
from  ipt_mkt_area_kpi_target_hz
group by areaname,cityname,projectid,periodid,productid
),
T5 AS (  -- 从目标录入表中取目标
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,PERIODID,PRODUCTID,VERSION,'存货'sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN STOCK_ORDER ELSE 0 END),2)  MPLANAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN STOCK_ORDER ELSE 0 END),2) TPLANAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = LEFT('${YEARMONTH}',4)  THEN STOCK_ORDER ELSE 0 END),2) YPLANAMOUNT
FROM  IPT_MKT_AREA_KPI_TARGET 
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID,VERSION
UNION ALL
SELECT areaname,max(cityname)cityname,max(projectid)projectid,projectname,periodname,max(RATIO)RATIO,max(HF_RATIO)HF_RATIO,PERIODID ,PRODUCTID,VERSION,'新取证'sale_type,
ROUND(SUM(CASE WHEN YEARMONTH = '${YEARMONTH}' THEN NEW_ORDER ELSE 0 END),2)  MPLANAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH <= '${YEARMONTH}' AND LEN(YEARMONTH)=7 THEN NEW_ORDER ELSE 0 END),2) TPLANAMOUNT,
ROUND(SUM(CASE WHEN YEARMONTH = LEFT('${YEARMONTH}',4)  THEN NEW_ORDER ELSE 0 END),2) YPLANAMOUNT
FROM  IPT_MKT_AREA_KPI_TARGET 
GROUP BY areaname,projectname,periodname,PERIODID ,PRODUCTID,VERSION
)

SELECT 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END BELONG_COMP, " ) }
${ if(INARRAY("1", SPLIT(dims, ",")) = 0,""," ISNULL(T1.AREANAME,T5.AREANAME)AREANAME, " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME)SHORTNAME, " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME) CITYNAME, " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME)PROJECTNAME,ISNULL(T3.RATIO,T5.RATIO)RATIO,ISNULL(T3.HF_RATIO,T5.HF_RATIO)HF_RATIO," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME)PERIODNAME,ISNULL(T1.PERIODID,T5.PERIODID)PERIODID," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)SALE_TYPE, " ) }
'a' a,
${SWITCH(TAB,0,"SUM(MORDERAMOUNT)",1,"SUM(MORDERAMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(MORDERAMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")} MORDERAMOUNT, 
${SWITCH(TAB,0,"SUM(YORDERAMOUNT)",1,"SUM(YORDERAMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YORDERAMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YORDERAMOUNT,
${SWITCH(TAB,0,"SUM(KS_AMOUNT)",1,"SUM(KS_AMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(KS_AMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}KS_AMOUNT,
${SWITCH(TAB,0,"SUM(MPLANAMOUNT)",1,"SUM(MPLANAMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(MPLANAMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}MPLANAMOUNT, 
${SWITCH(TAB,0,"SUM(TPLANAMOUNT)",1,"SUM(TPLANAMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(TPLANAMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}TPLANAMOUNT,
${SWITCH(TAB,0,"SUM(YPLANAMOUNT)",1,"SUM(YPLANAMOUNT*ISNULL(T3.RATIO,T5.RATIO))",2,"SUM(YPLANAMOUNT*ISNULL(T3.HF_RATIO,T5.HF_RATIO))")}YPLANAMOUNT
FROM T1 
LEFT JOIN T2 ON T1.PERIODID=T2.PERIODID AND T1.PRODUCTID = T2.PRODUCTID AND T1.SALE_TYPE = T2.SALE_TYPE
LEFT JOIN (SELECT DISTINCT PERIODID,PERIODNAME,RATIO,HF_RATIO,CP_FLAG FROM DIM_MKT_PROJECT) T3 ON T1.PERIODID = T3.PERIODID
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T4 ON T1.PRODUCTID=T4.PRODUCTID
FULL JOIN T5 ON T1.PERIODID = T5.PERIODID AND t1.PRODUCTID = T5.PRODUCTID  AND T1.SALE_TYPE = T5.SALE_TYPE
LEFT JOIN (SELECT DISTINCT PRODUCTID,SHORTNAME FROM DIM_PRODUCT_TYPE) T6 ON T5.PRODUCTID=T6.PRODUCTID


WHERE 1=1
-- ${if(len(AREA)=0,"","and T1.AREANAME in ('"+AREA+"')")}
${if(len(CITY)=0,"","and ISNULL(T1.CITYNAME,T5.CITYNAME) in ('"+CITY+"')")}
${if(len(PRO) == 0,"","and ISNULL(T1.PROJECTID,T5.PROJECTID) in ('" + PRO+ "')")}
${if(len(DUCT) == 0,"","and ISNULL(left(T4.PRODUCTID,4),left(T6.PRODUCTID,4))  in ('" + DUCT + "')")}
${if(len(SALE_TYPE) == 0,"","and T1.SALE_TYPE  in ('" + SALE_TYPE+ "')")}
${if(len(BELONG_COMP) == 0,"","and CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END in ('" + BELONG_COMP+ "')")}
AND ISNULL(T1.AREANAME,T5.AREANAME) = '珠海大区'

GROUP BY
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END, " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,""," ISNULL(T4.SHORTNAME,T6.SHORTNAME), " ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," ISNULL(T1.CITYNAME,T5.CITYNAME), " ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE), " ) }
ISNULL(T1.AREANAME,T5.AREANAME)


ORDER BY 
${ if(INARRAY("0", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(CASE  WHEN ISNULL(T3.RATIO,T5.RATIO) = 0  AND ISNULL(T3.HF_RATIO,T5.HF_RATIO) >0 THEN '城运托管' ELSE '股份项目' END,'股份项目|城运托管'), " ) }
${ if(INARRAY("2", SPLIT(dims, ",")) = 0,"","CHARINDEX(ISNULL(T4.SHORTNAME,T6.SHORTNAME),'住宅|别墅|商业|车位')," ) }
${ if(INARRAY("3", SPLIT(dims, ",")) = 0,""," 
CHARINDEX(ISNULL(T1.CITYNAME,T5.CITYNAME),'珠海华欣|珠海华景|珠海西区'),
" ) }
${ if(INARRAY("4", SPLIT(dims, ",")) = 0,"","  ISNULL(T1.PROJECTNAME,T5.PROJECTNAME),ISNULL(T3.RATIO,T5.RATIO),ISNULL(T3.HF_RATIO,T5.HF_RATIO)," ) }
${ if(INARRAY("5", SPLIT(dims, ",")) = 0,""," ISNULL(T1.PERIODNAME,T5.PERIODNAME),ISNULL(T1.PERIODID,T5.PERIODID)," ) }
${ if(INARRAY("6", SPLIT(dims, ",")) = 0,""," ISNULL(T1.SALE_TYPE,T5.SALE_TYPE)," ) }
a

SELECT DISTINCT THE_MONTH FROM DIM_TIME 
WHERE LEFT(THE_MONTH,4) = CONVERT(VARCHAR(4),GETDATE()-1,120)
AND THE_MONTH < = CONVERT(VARCHAR(7),GETDATE()-1,120)
AND THE_MONTH >'2021-02'

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

select AREANAME FROM (
SELECT  distinct AREANAME 
FROM   DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)) A
WHERE AREANAME = '珠海大区'


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT CITYNAME FROM (
select distinct CITYNAME from DIM_MKT_PROJECT 
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
and AREANAME = '珠海大区'
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")} ) A


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT DISTINCT PROJECTID,'('+PROJECTID+')'+ ISNULL(SALERGROUPNAME,PROJECTNAME) PROJECTNAME FROM DIM_MKT_PROJECT
WHERE PROJECTID IN
(
	SELECT DISTINCT DEPT_ID FROM user_org 
)  
and AREANAME = '珠海大区'
${if(len(AREA) == 0,"","and AREANAME in ('" + AREA + "')")}
${if(len(CITY) == 0,"","and CITYNAME in ('" + CITY + "')")}

SELECT DISTINCT PRODUCTID,PRODUCTNAME FROM DIM_PRODUCT_TYPE WHERE PRODUCT_TYPE = '02'


SELECT MAX (INSERTIME) INSERTIME FROM F_MKT_PROJECT_SALE


select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01')) else 1 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofmonth(curdate())/ datediff(concat(left(date_add(curdate(), interval 1 month),7),'-01'),concat(left(curdate(),7),'-01'))*100,2) else 100 end

select case when left(curdate(),7) = '${YEARMONTH}' then 
dayofyear(curdate())/ 365 
else datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365 end,

case when left(curdate(),7) = '${YEARMONTH}' then 
round(dayofyear(curdate())/ 365*100,2) 
else round(datediff(concat('${YEARMONTH}','-28'),concat(left(curdate(),4),'-01-01'))/365*100,2) end




