SELECT * FROM FR_T_MARGIN_PAYABLE_TEMP
WHERE DJRQ BETWEEN TO_DATE('${P_S_DATE}'||' 00:00:00','yyyy-MM-dd HH24:mi:ss') AND TO_DATE('${P_E_DATE}'||' 00:00:00','yyyy-MM-dd HH24:mi:ss')
AND BMBM IN ('${P_DEPT_ID}')
ORDER BY DJRQ

SELECT DISTINCT BMBM,BMMC FROM FR_T_MARGIN_PAYABLE ORDER BY BMBM

