SELECT * FROM FR_ETL_TIME 
WHERE 1=1
${IF(LEN(P_TABLE)=0,"","AND TABLE_ID ='"+P_TABLE+"'")}
ORDER BY TABLE_ID,S_DATE

SELECT 'FR_T_MAIN_BUSINESS_INCOME' TABLE_ID,'主营业务收入' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_MAIN_BUSINESS_COST' TABLE_ID,'主营业务支出' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_NCF_INCOME' TABLE_ID,'净现金流-资金流入' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_NCF_EXPENSE' TABLE_ID,'净现金流-资金流出' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_OVERDUE_RECEIVABLES' TABLE_ID,'逾期账龄-应收账款' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_OVERDUE_BORROWYING' TABLE_ID,'逾期账龄-待还借款' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_BORROWYING_DETAIL' TABLE_ID,'借款明细表' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_PROCEEDS_DETAILS' TABLE_ID,'费用小精灵-收款明细' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_RECEIVABLES' TABLE_ID,'应收回款表' AS TABLE_NAME FROM DUAL
UNION ALL
SELECT 'FR_T_CONTRACT' TABLE_ID,'新签合同' AS TABLE_NAME FROM DUAL

