SELECT MAX(INSERTIME) INSERTIME FROM F_MKT_SALE_MONTHKPI
WHERE YEARMONTH='${YEARMONTH}'

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)
SELECT  AREANAME FROM DIM_MKT_PROJECT
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
GROUP BY AREANAME
order by charindex(AREANAME,'珠海大区|华南大区|华东大区|北方大区|北京区域')

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)
SELECT  DISTINCT PROJECTID,PROJECTID+'-'+PROJECTNAME PROJECTNAME FROM DIM_MKT_PROJECT
WHERE  PROJECTID IN
(
 SELECT DISTINCT DEPT_ID FROM user_org
)
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}
${if(len(CITYNAME)=0,""," AND CITYNAME IN ('"+CITYNAME+"')")}

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT  DISTINCT CITYNAME FROM DIM_MKT_PROJECT
WHERE  PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)  
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)
, P AS 
(SELECT DISTINCT
	PROJECTID,
	PROJECTNAME,
	PERIODID,
  RATIO,
  HF_RATIO
FROM
	DIM_MKT_PROJECT
WHERE
	PROJECTID IN (
		SELECT DISTINCT
			PROJECTID
		FROM
			GET_MKT_PROJECT_TB ('${fr_username}')
	)
), T0 AS 
(SELECT
  A.AREANAME,
  A.CITYNAME,
	A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
	A.PERIODNAME,
	T3.SHORTNAME,
  SUM(ORDERSUIT) ORDERSUIT,
  SUM(ORDERAREA) ORDERAREA,
  SUM(ORDERAMOUNT) ORDERAMOUNT,
  SUM(ORDERSUIT*RATIO) QORDERSUIT,
  SUM(ORDERAREA*RATIO) QORDERAREA,
  SUM(ORDERAMOUNT*RATIO) QORDERAMOUNT,
	SUM(ORDERSUIT*HF_RATIO) HFORDERSUIT,
  SUM(ORDERAREA*HF_RATIO) HFORDERAREA,
  SUM(ORDERAMOUNT*HF_RATIO) HFORDERAMOUNT,
  SUM(SIGNSUIT) SIGNSUIT,
  SUM(SIGNAREA) SIGNAREA,
  SUM(SIGNAMOUNT) SIGNAMOUNT,
  SUM(SIGNSUIT*RATIO) QSIGNSUIT,
  SUM(SIGNAREA*RATIO) QSIGNAREA,
  SUM(SIGNAMOUNT*RATIO) QSIGNAMOUNT,
	SUM(SIGNSUIT*HF_RATIO) HFSIGNSUIT,
  SUM(SIGNAREA*HF_RATIO) HFSIGNAREA,
  SUM(SIGNAMOUNT*HF_RATIO) HFSIGNAMOUNT
FROM
	F_MKT_PROJECT_SALE A
INNER JOIN P ON A.PERIODID=P.PERIODID 
LEFT JOIN DIM_PRODUCT_TYPE T3 ON A.PRODUCTID=T3.PRODUCTID
WHERE LEFT(DATE,7)='${yearmonth}'
GROUP BY 
  A.AREANAME,
  A.CITYNAME,
	A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
	A.PERIODNAME,
	T3.SHORTNAME
),T1 AS
(SELECT
  A.AREANAME,
  A.CITYNAME,
	A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
	A.PERIODNAME,
	T3.SHORTNAME,
  SUM(ORDERSUIT) ORDERSUIT,
  SUM(ORDERAREA) ORDERAREA,
  SUM(ORDERAMOUNT) ORDERAMOUNT,
  SUM(QY_ORDERSUIT) QORDERSUIT,
  SUM(QY_ORDERAREA) QORDERAREA,
  SUM(QY_ORDERAMOUNT) QORDERAMOUNT,
	SUM(ORDERSUIT*HF_RATIO) HFORDERSUIT,
  SUM(ORDERAREA*HF_RATIO) HFORDERAREA,
  SUM(ORDERAMOUNT*HF_RATIO) HFORDERAMOUNT,
  SUM(SIGNSUIT) SIGNSUIT,
  SUM(SIGNAREA) SIGNAREA,
  SUM(SIGNAMOUNT) SIGNAMOUNT,
  SUM(QY_SIGNSUIT) QSIGNSUIT,
  SUM(QY_SIGNAREA) QSIGNAREA,
  SUM(QY_SIGNAMOUNT) QSIGNAMOUNT,
	SUM(SIGNSUIT*HF_RATIO) HFSIGNSUIT,
  SUM(SIGNAREA*HF_RATIO) HFSIGNAREA,
  SUM(SIGNAMOUNT*HF_RATIO) HFSIGNAMOUNT
FROM
	F_MKT_SALE_MONTHKPI A
LEFT JOIN DIM_PRODUCT_TYPE T3 ON A.PRODUCTID=T3.PRODUCTID
LEFT JOIN P ON A.PERIODID=P.PERIODID 
WHERE YEARMONTH='${yearmonth}'
GROUP BY 
  A.AREANAME,
  A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
	A.PERIODNAME,
	T3.SHORTNAME
),TT AS 
(SELECT '1' AS TT)
SELECT 
  ${ if(INARRAY("1", SPLIT(groupItems, ",")) = 0,""," ISNULL(T0.AREANAME,T1.AREANAME) AREANAME," ) } 
  ${ if(INARRAY("2", SPLIT(groupItems, ",")) = 0,""," ISNULL(T0.CITYNAME,T1.CITYNAME) CITYNAME," ) } 
  ${ if(INARRAY("3", SPLIT(groupItems, ",")) = 0,""," ISNULL(T0.PROJECTNAME,T1.PROJECTNAME)PROJECTNAME," ) } 
  ${ if(INARRAY("4", SPLIT(groupItems, ",")) = 0,"","ISNULL(T0.SHORTNAME,T1.SHORTNAME) SHORTNAME," ) } 
  SUM(T0.ORDERSUIT) MORDERSUIT,
  SUM(T0.ORDERAREA) MORDERAREA,
  SUM(T0.ORDERAMOUNT/10000)  MORDERAMOUNT,
  SUM(T0.QORDERSUIT) QMORDERSUIT,
  SUM(T0.QORDERAREA) QMORDERAREA,
  SUM(T0.QORDERAMOUNT/10000)  QMORDERAMOUNT,
  SUM(T0.HFORDERSUIT) HFMORDERSUIT,
  SUM(T0.HFORDERAREA) HFMORDERAREA,
  SUM(T0.HFORDERAMOUNT/10000)  HFMORDERAMOUNT,
  SUM(T1.ORDERSUIT) KJMORDERSUIT,
  SUM(T1.ORDERAREA) KJMORDERAREA,
  SUM(T1.ORDERAMOUNT/10000)  KJMORDERAMOUNT,
  SUM(T1.QORDERSUIT) KJQMORDERSUIT,
  SUM(T1.QORDERAREA) KJQMORDERAREA,
  SUM(T1.QORDERAMOUNT/10000)  KJQMORDERAMOUNT,
  SUM(T1.HFORDERSUIT) KJHFMORDERSUIT,
  SUM(T1.HFORDERAREA) KJHFMORDERAREA,
  SUM(T1.HFORDERAMOUNT/10000)  KJHFMORDERAMOUNT,
  SUM(T0.SIGNSUIT) MSIGNSUIT,
  SUM(T0.SIGNAREA) MSIGNAREA,
  SUM(T0.SIGNAMOUNT/10000)  MSIGNAMOUNT,
  SUM(T0.QSIGNSUIT) QMSIGNSUIT,
  SUM(T0.QSIGNAREA) QMSIGNAREA,
  SUM(T0.QSIGNAMOUNT/10000)  QMSIGNAMOUNT,
  SUM(T0.HFSIGNSUIT) HFMSIGNSUIT,
  SUM(T0.HFSIGNAREA) HFMSIGNAREA,
  SUM(T0.HFSIGNAMOUNT/10000)  HFMSIGNAMOUNT,
  SUM(T1.SIGNSUIT) KJSIGNSUIT,
  SUM(T1.SIGNAREA) KJSIGNAREA,
  SUM(T1.SIGNAMOUNT/10000)  KJSIGNAMOUNT,
  SUM(T1.QSIGNSUIT) KJQSIGNSUIT,
  SUM(T1.QSIGNAREA) KJQSIGNAREA,
  SUM(T1.QSIGNAMOUNT/10000)  KJQSIGNAMOUNT,
  SUM(T1.HFSIGNSUIT) KJHFSIGNSUIT,
  SUM(T1.HFSIGNAREA) KJHFSIGNAREA,
  SUM(T1.HFSIGNAMOUNT/10000)  KJHFSIGNAMOUNT,
  C.TT
FROM T0 FULL JOIN T1 ON T0.PERIODID=T1.PERIODID AND T0.SHORTNAME=T1.SHORTNAME
LEFT JOIN TT C ON 1=1
WHERE ISNULL(T0.PROJECTID,T1.PROJECTID) IN
(
	 SELECT DISTINCT DEPT_ID FROM user_org
)
  ${if(len(areaName)=0,"","AND ISNULL(T0.AREANAME,T1.AREANAME) IN ('"+areaName+"')")}
  ${if(len(CITYNAME)=0,"","AND ISNULL(T0.CITYNAME,T1.CITYNAME) IN ('"+CITYNAME+"')")}
  ${if(len(PROJECTID)=0,"","AND ISNULL(T0.PROJECTID,T1.PROJECTID) IN ('"+PROJECTID+"')")}
GROUP BY 
  ${if(INARRAY("1", SPLIT(groupItems,",")) = 0,"","ISNULL(T0.AREANAME,T1.AREANAME),")} 
  ${if(INARRAY("2", SPLIT(groupItems,",")) = 0,"","ISNULL(T0.CITYNAME,T1.CITYNAME),")} 
  ${if(INARRAY("3", SPLIT(groupItems,",")) = 0,"","ISNULL(T0.PROJECTNAME,T1.PROJECTNAME),")} 
  ${if(INARRAY("4", SPLIT(groupItems,",")) = 0,"","ISNULL(T0.SHORTNAME,T1.SHORTNAME)," )} 
  C.TT
ORDER BY 
  ${if(INARRAY("1", SPLIT(groupItems,",")) = 0,"","charindex(ISNULL(T0.AREANAME,T1.AREANAME),'珠海大区|华南大区|华东大区|北方大区|北京区域'),")} 
  ${if(INARRAY("2", SPLIT(groupItems,",")) = 0,"","charindex(ISNULL(T0.CITYNAME,T1.CITYNAME),'珠海华欣|珠海华景珠海西区|中山|广州|南宁|上海|南京|沈阳|大连|包头|'),")} 
  ${if(INARRAY("3", SPLIT(groupItems,",")) = 0,"","ISNULL(T0.PROJECTNAME,T1.PROJECTNAME),")} 
  ${if(INARRAY("4", SPLIT(groupItems,",")) = 0,"","charindex(ISNULL(T0.SHORTNAME,T1.SHORTNAME),'住宅|商业|车位|')," )} 
 C.TT

SELECT distinct SHORTNAME FROM DIM_PRODUCT_TYPE

