
SELECT 
  YEARMONTH,
  STATUS,
  CONVERT(VARCHAR(10),UPDATETIME,120) UPDATETIME,
  UPDATEUSER,
	SUM(ORDERSUIT) ORDERSUIT,
	SUM(ORDERAREA) ORDERAREA,
	SUM(ORDERAMOUNT)/10000 ORDERAMOUNT,
  SUM(QY_ORDERSUIT) QORDERSUIT,
	SUM(QY_ORDERAREA) QORDERAREA,
	SUM(QY_ORDERAMOUNT)/10000 QORDERAMOUNT,
  SUM(SIGNSUIT) SIGNSUIT,
	SUM(SIGNAREA) SIGNAREA,
	SUM(SIGNAMOUNT)/10000 SIGNAMOUNT,
  SUM(QY_SIGNSUIT) QSIGNSUIT,
	SUM(QY_SIGNAREA) QSIGNAREA,
	SUM(QY_SIGNAMOUNT)/10000 QSIGNAMOUNT
FROM
	F_MKT_SALE_MONTH
WHERE
  LEFT(YEARMONTH,4)='${SYEAR}'
  ${if(len(areaName)=0,"","AND AREANAME IN ('"+areaName+"')")}
  ${if(len(CITYNAME)=0,"","AND CITYNAME IN ('"+CITYNAME+"')")}

 GROUP BY 
	YEARMONTH,STATUS,CONVERT(VARCHAR(10),UPDATETIME,120),UPDATEUSER
ORDER BY 
   YEARMONTH DESC 

SELECT  AREANAME FROM DIM_MKT_PROJECT
GROUP BY AREANAME
order by charindex(AREANAME,'珠海区域|华南区域|华东区域|华中区域|北方区域|山东区域|北京公司')

SELECT  DISTINCT CITYNAME FROM DIM_MKT_PROJECT
WHERE 1=1
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}

SELECT DISTINCT LEFT(YEARMONTH,4)SYEAR FROM F_MKT_SALE_MONTH

