SELECT
	B.FNUMBER AS 部门编码,--部门编码
	B.FNAME_L2 AS 部门,--部门名称
	C.FNUMBER AS 业务科室编码,--业务科室编码
	C.FNAME_L2 AS 业务科室,--业务科室名称
	A.FNUMBER AS 项目编码,--项目编码
	A.FNAME_L2 AS 项目, --项目名称
	D.FNUMBER AS 项目经理编码,--项目经理编码
	D.FNAME_L2 AS 项目经理,--项目经理名称
	D.FCELL AS 手机号码
FROM T_DXQ_PROJECTITEM A
LEFT JOIN T_ORG_BASEUNIT  B ON A.CFADMINORUNITID=B.FID
LEFT JOIN T_ORG_BASEUNIT  C ON A.CFBIZORGID=C.FID
LEFT JOIN T_BD_PERSON  D ON A.FPROJECTMANAGERID=D.FID

--捷云组织架构
SELECT
 P1.FNUMBER AS 组织ID,
 P1.FNAME_L2 AS 组织名称,
 P3.FNUMBER AS 上级组织ID,
 P3.FNAME_L2 上级组织,
 P1.FLEVEL AS 组织级次,
 REPLACE(P1.FLONGNUMBER,'!','_') FULLPATH,
 P1.FDISPLAYNAME_L2 FULLPATH_NAME
FROM T_ORG_BASEUNIT P1
LEFT JOIN T_ORG_BASEUNIT P3 ON P1.FPARENTID = P3.FID AND P3.FNUMBER NOT LIKE '%作废%'
WHERE P1.FNUMBER NOT LIKE '%作废%'
AND EXISTS (SELECT P2.FID FROM T_ORG_BASEUNIT P2 WHERE P2.FNUMBER NOT LIKE '%作废%' AND P1.FID = P2.FID)
START WITH P1.FPARENTID IS NULL
CONNECT BY P1.FPARENTID = PRIOR P1.FID
ORDER BY P1.FDISPLAYNAME_L2

SELECT DISTINCT
	FR_DEPT_ID, --帆软平台部门编码
	DEPT_ID, --捷云部门编码
	PARENT_ID, --捷云父级部门编码
	DEPT_NAME, --部门名称
	DEPT_TYPE, --部门类型 1:职能部门 2:业务部门
	USERNAME, --登录名
	REALNAME --姓名
FROM FR_DEPT_ROLE_USER
WHERE 1=1
${IF(LEN(P_DEPT)=0,"","AND DEPT_ID ='"+P_DEPT+"'")}

SELECT DISTINCT
	A.FR_DEPT_ID, --帆软平台部门编码
	A.DEPT_ID, --捷云部门编码
	A.PARENT_ID, --捷云父级部门编码
	A.DEPT_NAME, --部门名称
	A.DEPT_TYPE, --部门类型 1:职能部门 2:业务部门
	A.USERNAME, --登录名
	A.REALNAME, --姓名
	B.AUTHORIZATION,--授权项目
	B.GUID
FROM FR_DEPT_ROLE_USER A
LEFT JOIN (
SELECT
	GUID,
	USERNAME, --登录名
	REALNAME, --姓名
	DEPT_ID, --部门ID (捷云系统部门ID)
	DEPT_NAME, --部门名称
	PARENT_ID, --父级ID(捷云系统部门ID)
	DEPT_TYPE,--部门类型(1:职能部门 2:业务部门)
	LV,--授权等级
	AUTHORIZATION --授权内容
FROM FR_USR_AUZ
WHERE LV = 2
)B ON A.USERNAME = B.USERNAME
WHERE 1=1
AND A.USERNAME = '${P_USER}'

--捷云组织架构
SELECT
 P1.FNUMBER AS 组织ID,
 P1.FNAME_L2 AS 组织名称,
 P3.FNUMBER AS 上级组织ID,
 P3.FNAME_L2 上级组织,
 P1.FLEVEL AS 组织级次,
 REPLACE(P1.FLONGNUMBER,'!','_') FULLPATH,
 P1.FDISPLAYNAME_L2 FULLPATH_NAME
FROM T_ORG_BASEUNIT P1
LEFT JOIN T_ORG_BASEUNIT P3 ON P1.FPARENTID = P3.FID AND P3.FNUMBER NOT LIKE '%作废%'
WHERE P1.FNUMBER NOT LIKE '%作废%'
AND P1.FLEVEL = 3
AND EXISTS (SELECT P2.FID FROM T_ORG_BASEUNIT P2 WHERE P2.FNUMBER NOT LIKE '%作废%' AND P1.FID = P2.FID)
START WITH P1.FPARENTID IS NULL
CONNECT BY P1.FPARENTID = PRIOR P1.FID
ORDER BY P1.FNUMBER

