SELECT DEPT_ID,DEPT_NAME FROM  FR_ORG
order by DEPT_LEVEL,DEPT_ID

select 
USER_ID,USER_NAME,DEPT_ID,DEPT_NAME
from fr_user_org a
WHERE 1=1
 ${if(find("全部",userId)>0,"","AND USER_ID ='"+userId+"'")}
 ${if(len(DEPT_ID)=0,"","AND DEPT_ID IN ('"+DEPT_ID+"')")}
AND ORG_TYPE='组织'

WITH C AS (
	SELECT DISTINCT
    A.DEPTID,
		A.PARENTID,
		B.DEPTNAME PARENTNAME
	FROM
		DIM_DEPT A
	LEFT JOIN DIM_DEPT B ON A.PARENTID = B.DEPTID
) SELECT
	B.USERID,
	C.PARENTNAME+'-'+B.DEPTNAME+'-'+B.USERNAME USERNAME
FROM
 DIM_USER B
LEFT JOIN  C ON B.DEPTID = C.DEPTID
WHERE PARENTNAME IS NOT NULL

select distinct org_type from fr_org

