SELECT MAX(INSERTIME) INSERTIME FROM F_MKT_SALE_MONTH
WHERE YEARMONTH='${YEARMONTH}'

WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)

SELECT  AREANAME FROM  DIM_MKT_PROJECT 
WHERE  PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
GROUP BY AREANAME
order by charindex(AREANAME,'珠海区域|华南区域|华东区域|华中区域|北方区域|山东区域|北京公司')


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)
SELECT  DISTINCT PROJECTID,PROJECTNAME  FROM  DIM_MKT_PROJECT 
WHERE  PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}
${if(len(CITYNAME)=0,""," AND CITYNAME IN ('"+CITYNAME+"')")}


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
)
SELECT  DISTINCT CITYNAME FROM DIM_MKT_PROJECT 
WHERE  PROJECTID IN
(
	SELECT DEPT_ID FROM user_org 
)
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}


WITH user_org as
(
  select * from fr_org where dept_id in (
		select dept_id from fr_user_org
			where user_id='${fine_username}' )
  UNION ALL
  select t.* from fr_org t inner join user_org tcte on t.parent_id = tcte.dept_id
),

T0 AS 
(SELECT
  LEFT('${YEARMONTH}',4)+'年度(1-'+CAST(MONTH('${YEARMONTH}'+'-01') as varchar(2))+'月)' YEARMONTH,
  B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*RATIO) QY_INCOMEAMOUNT,
  SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT
FROM
	F_MKT_PROJECT_SALE A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE
	LEFT(DATE,7) BETWEEN LEFT('${YEARMONTH}',4)+'-01' AND '${YEARMONTH}'
GROUP BY
	B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME
),T5 AS 
(SELECT
  AREANAME,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME,
  SUM (DDAMOUNT) DDAMOUNT,
  SUM (WDAMOUNT) WDAMOUNT,
  SUM (DDAMOUNT*RATIO) QY_DDAMOUNT,
  SUM (WDAMOUNT*RATIO) QY_WDAMOUNT,
  SUM (DDAMOUNT*HF_RATIO) HF_DDAMOUNT,
  SUM (WDAMOUNT*HF_RATIO) HF_WDAMOUNT
FROM
	F_MKT_PROJECT_SIGN A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE LEFT(CREDATE,7) BETWEEN LEFT('${YEARMONTH}',4)+'-01' AND '${YEARMONTH}'
GROUP BY
  AREANAME,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME
),T7 AS 
(SELECT
  A.PERIODID,
  C.SHORTNAME,
  SUM (INCOMEAMOUNT) DYINCOMEAMOUNT,
  SUM (INCOMEAMOUNT*RATIO) QY_DYINCOMEAMOUNT,
	SUM (INCOMEAMOUNT*HF_RATIO) HF_DYINCOMEAMOUNT,
  SUM (QYINCOMEAMOUNT) QYINCOMEAMOUNT,
  SUM (QYINCOMEAMOUNT*RATIO) QY_QYINCOMEAMOUNT,
	SUM (QYINCOMEAMOUNT*HF_RATIO) HF_QYINCOMEAMOUNT
FROM
	F_MKT_ORDER_INCOME A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE
	YEARMONTH ='${YEARMONTH}'
GROUP BY
	A.PERIODID,
  C.SHORTNAME
),T6 AS 
(SELECT 
  YEARMONTH,
  T0.AREAID,
	T0.AREANAME,
  T0.CITYID,
	T0.CITYNAME,
  T0.PROJECTID,
	T0.PROJECTNAME,
	T0.PERIODID,
  T0.PERIODNAME,
  T0.SHORTNAME,
  CASE WHEN T0.PROJECTID LIKE 'HZ%' THEN 'N' ELSE 'Y' END CP_FLAG,
  ORDERAMOUNT,
  SIGNAMOUNT,
  INCOMEAMOUNT,
  QY_ORDERAMOUNT,
	QY_SIGNAMOUNT,
  QY_INCOMEAMOUNT,
	HF_ORDERAMOUNT,
	HF_SIGNAMOUNT,
  HF_INCOMEAMOUNT,
  DDAMOUNT,
  QY_DDAMOUNT,
	HF_DDAMOUNT,
  DYINCOMEAMOUNT,
  QY_DYINCOMEAMOUNT,
	HF_DYINCOMEAMOUNT,
  QYINCOMEAMOUNT,
  QY_QYINCOMEAMOUNT,
	HF_QYINCOMEAMOUNT
FROM T0 LEFT JOIN T5 ON T0.PERIODID=T5.PERIODID AND T0.SHORTNAME=T5.SHORTNAME
LEFT JOIN T7 ON T0.PERIODID=T7.PERIODID AND T0.SHORTNAME=T7.SHORTNAME
),T1 AS 
(SELECT --月度
  YEARMONTH+'月度' YEARMONTH,
  AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME,
  CASE WHEN PROJECTID LIKE 'HZ%' THEN 'N' ELSE 'Y' END  CP_FLAG,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*B.RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*B.RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*B.RATIO) QY_INCOMEAMOUNT,
	SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT,
  0 DDAMOUNT,
  0 QY_DDAMOUNT,
	0 HF_DDAMOUNT,
  0 DYINCOMEAMOUNT,
  0 QY_DYINCOMEAMOUNT,
	0 HF_DYINCOMEAMOUNT,
  0 QYINCOMEAMOUNT,
  0 QY_QYINCOMEAMOUNT,
	0 HF_QYINCOMEAMOUNT
FROM
	F_MKT_SALE_MONTHKPI A
LEFT JOIN (SELECT DISTINCT PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE YEARMONTH='${YEARMONTH}'
GROUP BY
  YEARMONTH,
	AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
		A.PERIODID,
  PERIODNAME,
	SHORTNAME
),T2 AS 
(SELECT
  LEFT('${YEARMONTH}',4)+'第一季度(1-3月)' YEARMONTH,
  B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME,
  CASE WHEN A.PROJECTID LIKE 'HZ%' THEN 'N' ELSE 'Y' END CP_FLAG,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*RATIO) QY_INCOMEAMOUNT,
	SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT,
 0 DDAMOUNT,
  0 QY_DDAMOUNT,
	0 HF_DDAMOUNT,
  0 DYINCOMEAMOUNT,
  0 QY_DYINCOMEAMOUNT,
	0 HF_DYINCOMEAMOUNT,
  0 QYINCOMEAMOUNT,
  0 QY_QYINCOMEAMOUNT,
	0 HF_QYINCOMEAMOUNT
FROM
	F_MKT_PROJECT_SALE A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE
	LEFT(DATE,7) BETWEEN LEFT('${YEARMONTH}',4)+'-01' AND LEFT('${YEARMONTH}',4)+'-03'
GROUP BY
	B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME
),T3 AS 
(SELECT
  LEFT('${YEARMONTH}',4)+'半年度(1-6月)' YEARMONTH,
  B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME,
  CASE WHEN A.PROJECTID LIKE 'HZ%' THEN 'N' ELSE 'Y' END CP_FLAG,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*RATIO) QY_INCOMEAMOUNT,	
	SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT,
  0 DDAMOUNT,
  0 QY_DDAMOUNT,
	0 HF_DDAMOUNT,
  0 DYINCOMEAMOUNT,
  0 QY_DYINCOMEAMOUNT,
	0 HF_DYINCOMEAMOUNT,
  0 QYINCOMEAMOUNT,
  0 QY_QYINCOMEAMOUNT,
	0 HF_QYINCOMEAMOUNT
FROM
	F_MKT_PROJECT_SALE A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE
	LEFT(DATE,7) BETWEEN LEFT('${YEARMONTH}',4)+'-01' AND LEFT('${YEARMONTH}',4)+'-06'
GROUP BY
	B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME
),A AS 
(SELECT
  AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*B.RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*B.RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*B.RATIO) QY_INCOMEAMOUNT,	
	SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT
FROM
	F_MKT_SALE_MONTH A
LEFT JOIN (SELECT DISTINCT PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE YEARMONTH=LEFT('${YEARMONTH}',4)+'-09'
GROUP BY
	AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME
),B AS 
(SELECT 
  AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME,
  SUM (ORDERAMOUNT) ORDERAMOUNT,
  SUM (SIGNAMOUNT) SIGNAMOUNT,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (ORDERAMOUNT*B.RATIO) QY_ORDERAMOUNT,
	SUM (SIGNAMOUNT*B.RATIO) QY_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*B.RATIO) QY_INCOMEAMOUNT,	
	SUM (ORDERAMOUNT*HF_RATIO) HF_ORDERAMOUNT,
	SUM (SIGNAMOUNT*HF_RATIO) HF_SIGNAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT
FROM
	F_MKT_SALE_MONTH A
LEFT JOIN (SELECT DISTINCT PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE YEARMONTH=LEFT('${YEARMONTH}',4)+'-06'
GROUP BY
	AREAID,
  AREANAME,
  CITYID,
	CITYNAME,
  PROJECTID,
	PROJECTNAME,
	A.PERIODID,
  PERIODNAME,
	SHORTNAME
),C AS 
(SELECT
  B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME,
  SUM (INCOMEAMOUNT) INCOMEAMOUNT,
  SUM (INCOMEAMOUNT*RATIO) QY_INCOMEAMOUNT,
  SUM (INCOMEAMOUNT*HF_RATIO) HF_INCOMEAMOUNT
FROM
	F_MKT_PROJECT_SALE A
LEFT JOIN (SELECT DISTINCT AREAID,CITYID,PERIODID,RATIO,HF_RATIO FROM DIM_MKT_PROJECT) B ON A.PERIODID=B.PERIODID
LEFT JOIN DIM_PRODUCT_TYPE C ON A.PRODUCTID=C.PRODUCTID
WHERE
	LEFT(DATE,7) BETWEEN LEFT('${YEARMONTH}',4)+'-07' AND LEFT('${YEARMONTH}',4)+'-09'
GROUP BY
	B.AREAID,
	A.AREANAME,
  B.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
  C.SHORTNAME
),T4 AS 
(SELECT 
  LEFT('${YEARMONTH}',4)+'第三季度(6-9月)' AS YEARMONTH,
  A.AREAID,
  A.AREANAME,
  A.CITYID,
	A.CITYNAME,
  A.PROJECTID,
	A.PROJECTNAME,
	A.PERIODID,
  A.PERIODNAME,
	A.SHORTNAME,
  CASE WHEN A.PROJECTID LIKE 'HZ%' THEN 'N' ELSE 'Y' END CP_FLAG,
  A.ORDERAMOUNT-B.ORDERAMOUNT ORDERAMOUNT,
  A.SIGNAMOUNT-B.SIGNAMOUNT SIGNAMOUNT,
  C.INCOMEAMOUNT,
  A.QY_ORDERAMOUNT-B.QY_ORDERAMOUNT QY_ORDERAMOUNT,
  A.QY_SIGNAMOUNT-B.QY_SIGNAMOUNT QY_SIGNAMOUNT,
	C.QY_INCOMEAMOUNT,
	A.HF_ORDERAMOUNT-B.HF_ORDERAMOUNT HF_ORDERAMOUNT,
  A.HF_SIGNAMOUNT-B.HF_SIGNAMOUNT HF_SIGNAMOUNT,
	C.HF_INCOMEAMOUNT,
  0 DDAMOUNT,
  0 QY_DDAMOUNT,
	0 HF_DDAMOUNT,
  0 DYINCOMEAMOUNT,
  0 QY_DYINCOMEAMOUNT,
	0 HF_DYINCOMEAMOUNT,
  0 QYINCOMEAMOUNT,
  0 QY_QYINCOMEAMOUNT,
	0 HF_QYINCOMEAMOUNT
FROM A LEFT JOIN B ON A.PERIODID=B.PERIODID AND A.SHORTNAME=B.SHORTNAME
LEFT JOIN C ON A.PERIODID=C.PERIODID AND A.SHORTNAME=C.SHORTNAME
)
 SELECT
  YEARMONTH,
  ${ if(INARRAY("1", SPLIT(counts, ",")) = 0,"","AREANAME,")}
  ${ if(INARRAY("2", SPLIT(counts, ",")) = 0,"","CITYNAME,")}
	${ if(INARRAY("3", SPLIT(counts, ",")) = 0,"","PROJECTID,")} 
	${ if(INARRAY("3", SPLIT(counts, ",")) = 0,"","PROJECTNAME,")} 
	${ if(INARRAY("4", SPLIT(counts, ",")) = 0,"","PERIODID,")} 
	${ if(INARRAY("4", SPLIT(counts, ",")) = 0,"","PERIODNAME,")}
	${ if(INARRAY("5", SPLIT(counts, ",")) = 0,"","SHORTNAME,")}
  ${SWITCH(KJ,0,"SUM(ORDERAMOUNT/10000)",1,"SUM(QY_ORDERAMOUNT/10000)",2,"SUM(HF_ORDERAMOUNT/10000)")} ORDERAMOUNT,
  ${SWITCH(KJ,0,"SUM(SIGNAMOUNT/10000)",1,"SUM(QY_SIGNAMOUNT/10000)",2,"SUM(HF_SIGNAMOUNT/10000)")} SIGNAMOUNT,
  ${SWITCH(KJ,0,"SUM(INCOMEAMOUNT/10000)",1,"SUM(QY_INCOMEAMOUNT/10000)",2,"SUM(HF_INCOMEAMOUNT/10000)")} INCOMEAMOUNT,
	${SWITCH(KJ,0,"SUM(DDAMOUNT/10000)",1,"SUM(QY_DDAMOUNT/10000)",2,"SUM(HF_DDAMOUNT/10000)")} DDAMOUNT,
	${SWITCH(KJ,0,"SUM(DYINCOMEAMOUNT/10000)",1,"SUM(QY_DYINCOMEAMOUNT/10000)",2,"SUM(HF_DYINCOMEAMOUNT/10000)")} DYINCOMEAMOUNT,
	${SWITCH(KJ,0,"SUM(QYINCOMEAMOUNT/10000)",1,"SUM(QY_QYINCOMEAMOUNT/10000)",2,"SUM(HF_QYINCOMEAMOUNT/10000)")} QYINCOMEAMOUNT,
  ${SWITCH(KJ,0,"CASE WHEN SUM(ORDERAMOUNT)=0 THEN 0 ELSE SUM(DDAMOUNT)/SUM(ORDERAMOUNT) END",1,"CASE WHEN SUM(QY_ORDERAMOUNT)=0 THEN 0 ELSE SUM(QY_DDAMOUNT)/SUM(QY_ORDERAMOUNT) END",2,"CASE WHEN SUM(HF_ORDERAMOUNT)=0 THEN 0 ELSE SUM(HF_DDAMOUNT)/SUM(HF_ORDERAMOUNT) END")} QYL,
  ${SWITCH(KJ,0,"CASE WHEN SUM(ORDERAMOUNT)=0 THEN 0 ELSE SUM(DYINCOMEAMOUNT)/SUM(ORDERAMOUNT) END",1,"CASE WHEN SUM(QY_ORDERAMOUNT)=0 THEN 0 ELSE SUM(QY_DYINCOMEAMOUNT)/SUM(QY_ORDERAMOUNT) END",2,"CASE WHEN SUM(HF_ORDERAMOUNT)=0 THEN 0 ELSE SUM(HF_DYINCOMEAMOUNT)/SUM(HF_ORDERAMOUNT) END")} RGL,
  ${SWITCH(KJ,0,"CASE WHEN SUM(DDAMOUNT)=0 THEN 0 ELSE SUM(QYINCOMEAMOUNT)/SUM(DDAMOUNT) END",1,"CASE WHEN SUM(QY_DDAMOUNT)=0 THEN 0 ELSE SUM(QY_QYINCOMEAMOUNT)/SUM(QY_DDAMOUNT) END",2,"CASE WHEN SUM(HF_DDAMOUNT)=0 THEN 0 ELSE SUM(HF_QYINCOMEAMOUNT)/SUM(HF_DDAMOUNT) END")} QHL
FROM ${TT}
WHERE PROJECTID IN
(
	SELECT DEPT_ID FROM user_org
)
${if(len(AREANAME)=0,""," AND AREANAME IN ('"+AREANAME+"')")}
${if(len(CITYNAME)=0,""," AND CITYNAME IN ('"+CITYNAME+"')")}
${if(len(PROJECTID)=0,""," AND PROJECTID IN ('"+PROJECTID+"')")}
${if(len(PRODUCTID)=0,""," AND SHORTNAME IN ('"+PRODUCTID+"')")}
${if(len(CP)=0,""," AND CP_FLAG IN ('"+CP+"')")}
GROUP BY 
  ${ if(INARRAY("1", SPLIT(counts, ",")) = 0,"","AREANAME,")}
  ${ if(INARRAY("2", SPLIT(counts, ",")) = 0,"","CITYNAME,")}
	${ if(INARRAY("3", SPLIT(counts, ",")) = 0,"","PROJECTID,")} 
	${ if(INARRAY("3", SPLIT(counts, ",")) = 0,"","PROJECTNAME,")} 
	${ if(INARRAY("4", SPLIT(counts, ",")) = 0,"","PERIODID,")} 
	${ if(INARRAY("4", SPLIT(counts, ",")) = 0,"","PERIODNAME,")}
	${ if(INARRAY("5", SPLIT(counts, ",")) = 0,"","SHORTNAME,")}
  YEARMONTH
ORDER BY 
${if(INARRAY("1", SPLIT(counts, ",")) = 0,"","charindex(AREANAME,'华南区域|华东区域|华中区域|山东区域|北方区域|北京公司|'),")}
${if(INARRAY("2", SPLIT(counts, ",")) = 0,"","charindex(CITYNAME,'珠海华欣|珠海华景珠海西区|中山|广州|南宁|上海|南京|沈阳|大连|包头|'),")}
${if(INARRAY("3", SPLIT(counts, ",")) = 0,"","PROJECTID,")} 
${if(INARRAY("4", SPLIT(counts, ",")) = 0,"","PERIODID,")}
${if(INARRAY("5", SPLIT(counts, ",")) = 0,"","charindex(SHORTNAME,'住宅|商业|车位|'),")} 
YEARMONTH

SELECT DISTINCT SHORTNAME FROM DIM_PRODUCT_TYPE
ORDER BY SHORTNAME

