SELECT 
	ID,--部门ID
	NAME,--部门名称
	PARENTID,--父ID
	DEPT_TYPE,--部门类型(职能:1/业务:2)
	(LENGTH(FULLPATH) - LENGTH(REPLACE(FULLPATH,'-_-','')))/3 + 1 AS 层级,
	ENABLE
FROM ZJTX.FINE_DEPARTMENT P1
WHERE 1=1
--ENABLE = 1
AND FULLPATH LIKE '0%'
AND PARENTID <> '0'
AND EXISTS (SELECT P2.ID FROM ZJTX.FINE_DEPARTMENT P2 WHERE P2.ENABLE = 1 AND P2.FULLPATH LIKE '0%' AND P1.ID = P2.ID)
START WITH P1.PARENTID ='0'
CONNECT BY P1.PARENTID = PRIOR P1.ID

WITH P AS (
SELECT
	A.DEPARTMENTID AS DEPT_ID, --部门ID
	B.NAME AS DEPT_NAME, -- 部门名称
	B.DEPT_TYPE, --部门分类ID
	CASE WHEN B.DEPT_TYPE = 1 THEN '职能部门'
	WHEN B.DEPT_TYPE = 2 THEN '业务部门'
	END AS DEPT_TYPE_NAME,
	A.POSTID AS POST_ID,-- 职位ID
	C.NAME AS POST_NAME, --职位名称
	E.USERNAME,
	E.REALNAME
FROM ZJTX.FINE_DEP_ROLE A
INNER JOIN ZJTX.FINE_DEPARTMENT B ON A.DEPARTMENTID = B.ID --部门表
INNER JOIN ZJTX.FINE_POST C ON A.POSTID = C.ID -- 职位表
LEFT JOIN ZJTX.FINE_USER_ROLE_MIDDLE D ON D.ROLEID = A.ID AND D.ROLETYPE = 1
LEFT JOIN ZJTX.FINE_USER E ON E.ID = D.USERID --用户表
WHERE B.FULLPATH LIKE '0-_-%' 
AND B.ENABLE = 1
AND C.ENABLE = 1
AND E.REALNAME NOT LIKE '初始化%'
AND E.ENABLE = 1
ORDER BY 
	A.DEPARTMENTID,
	A.POSTID
),R AS (
SELECT
	B.USERNAME,
	B.REALNAME,
	A.ROLEID,
	C.NAME AS ROLE_NAME
FROM ZJTX.FINE_USER_ROLE_MIDDLE A
LEFT JOIN ZJTX.FINE_USER B ON A.USERID = B.ID --用户表
LEFT JOIN (SELECT ID,NAME FROM ZJTX.fine_custom_role WHERE ENABLE = 1) C ON A.ROLEID = C.ID AND A.ROLETYPE = 2 --用户角色表
WHERE B.REALNAME NOT LIKE '初始化%'
AND B.ENABLE = 1
AND A.ROLETYPE = 2
AND C.NAME LIKE '财务市场%'
ORDER BY 
	B.USERNAME
)
SELECT * FROM P
LEFT JOIN R ON P.USERNAME = R.USERNAME

